import {test,expect} from '@playwright/test';
import {newGame,makeBuilding,makeUnit} from '../../src/game/state';
import {writeFile} from 'node:fs/promises';
test('production offline editing keeps a rotated damaged gate and once-paid battle rewards',async({page,context})=>{
 const s=newGame();s.speed=0;s.bountyPaid=40;s.completed=['build','recruit','night','claim','survive'];const gate=makeBuilding(s,'gate',19,15,true);gate.hp-=80;gate.level=2;gate.rotation=0;const zombie=makeUnit(s,'hollow',18,17);zombie.hp=1;
 await page.addInitScript(raw=>{if(!localStorage.getItem('kingnamic.save.v2'))localStorage.setItem('kingnamic.save.v2',raw);},JSON.stringify(s));await page.goto('/');await page.locator('#start').click();await page.locator('#speed-1').click();await expect(page.locator('#bounty-feedback')).toContainText('+1 Crowns');await page.locator('#pause').click();await page.locator('#tab-build').click();await page.locator('#category-owned').click();await page.locator('#inspect-'+gate.id).click();await page.locator('#edit-building').click();await page.locator('#rotate-placement').click();await expect(page.locator('#confirm-placement')).toBeEnabled();await page.locator('#confirm-placement').click();await page.locator('#save').click();await expect(page.locator('#save-status')).toHaveText('Saved on this device');
 await page.evaluate(()=>navigator.serviceWorker.ready);await page.waitForFunction(()=>!!navigator.serviceWorker.controller);const before=await page.evaluate(()=>JSON.parse(localStorage.getItem('kingnamic.save.v2')!));expect(before.bountyTotal).toBe(1);expect(before.buildings.find((b:any)=>b.id===gate.id)).toEqual({...gate,rotation:1});
 await context.setOffline(true);for(let n=0;n<2;n++){await page.reload();await page.locator('#start').click();await page.locator('#save').click();const after=await page.evaluate(()=>JSON.parse(localStorage.getItem('kingnamic.save.v2')!));expect(after.resources).toEqual(before.resources);expect(after.buildings).toEqual(before.buildings);expect(after.bountyTotal).toBe(1);expect(after.units.some((u:any)=>u.id===zombie.id)).toBe(false);}expect(await page.evaluate(()=>'__KINGNAMIC__' in window)).toBe(false);await writeFile('docs/evidence/correctness-offline.json',JSON.stringify({production:true,networkOffline:true,reloads:2,bountyTotal:before.bountyTotal,resources:before.resources,gate:before.buildings.find((b:any)=>b.id===gate.id)},null,2));await context.setOffline(false);
});
