import {test,expect} from '@playwright/test';
import {newGame,army} from '../../src/game/state';
import {command} from '../../src/game/commands';
import {ROAD_EXIT} from '../../src/game/empire';
import {advance} from '../../src/game/simulation';

test('production connected settlements preserve defenders, buildings, discovery and one-time rewards offline',async({page,context})=>{
 const s=newGame();s.resources={wood:500,stone:500,food:500,herbs:40};command(s,{type:'recruit',kind:'warden',count:2});command(s,{type:'commander-appoint'});const party=army(s).slice(0,3);for(const u of party)Object.assign(u,ROAD_EXIT);command(s,{type:'travel',ids:party.map(u=>u.id)});s.units=army(s);command(s,{type:'build',kind:'hearth',x:16,y:21});command(s,{type:'build',kind:'farm',x:18,y:21});advance(s,25);command(s,{type:'job',job:'builders',delta:-1});command(s,{type:'job',job:'farmers',delta:1});s.march!.seen=['village','grove','ruins'];const defenders=army(s).filter(u=>u.id!==s.commander!.id);command(s,{type:'order',order:'defend',ids:defenders.map(u=>u.id),x:16,y:20});Object.assign(army(s).find(u=>u.id===s.commander!.id)!,ROAD_EXIT);s.buildings.find(b=>b.kind==='farm')!.hp-=9;command(s,{type:'speed',speed:0});
 await page.addInitScript(raw=>{if(!localStorage.getItem('kingnamic.save.v2'))localStorage.setItem('kingnamic.save.v2',raw);},JSON.stringify(s));await page.goto('/');await page.locator('#start').click();await page.locator('#save').click();await expect(page.locator('#save-status')).toHaveText('Saved on this device');await page.evaluate(()=>navigator.serviceWorker.ready);await page.waitForFunction(()=>!!navigator.serviceWorker.controller);
 const before=await page.evaluate(()=>JSON.parse(localStorage.getItem('kingnamic.save.v2')!));await context.setOffline(true);await page.reload();await page.locator('#start').click();await expect(page.locator('#world-title')).toHaveText('Briar March');await page.locator('#tab-empire').click();await page.locator('#travel-region').click();await expect(page.locator('#world-title')).toHaveText('Hearthmere');await page.locator('#save').click();await expect(page.locator('#save-status')).toHaveText('Saved on this device');await page.reload();await page.locator('#start').click();await page.locator('#tab-empire').click();await page.locator('#travel-region').click();await page.locator('#save').click();const restored=await page.evaluate(()=>JSON.parse(localStorage.getItem('kingnamic.save.v2')!));
 expect(restored.resources).toEqual(before.resources);expect(restored.buildings).toEqual(before.buildings);expect(restored.residents).toEqual(before.residents);expect(restored.march).toEqual(before.march);expect(restored.jobs).toEqual(before.jobs);expect(restored.units.filter((u:any)=>defenders.some(d=>d.id===u.id))).toEqual(before.units.filter((u:any)=>defenders.some(d=>d.id===u.id)));expect(await page.evaluate(()=>'__KINGNAMIC__' in window)).toBe(false);await page.screenshot({path:'docs/evidence/empire-offline.png'});await context.setOffline(false);
});
