import {test,expect} from '@playwright/test';
import {writeFile} from 'node:fs/promises';
import {newGame,army,makeUnit} from '../../src/game/state';
import {command} from '../../src/game/commands';
import {infect,plagueStep} from '../../src/game/disease';
import {combatStep} from '../../src/game/combat';
const read=(p:any)=>p.evaluate(()=>JSON.parse(JSON.stringify((window as any).__KINGNAMIC__.runtime.state)));
function region(){const s=newGame();command(s,{type:'commander-appoint'});for(const u of army(s))Object.assign(u,{x:14,y:24});command(s,{type:'travel',ids:army(s).map(u=>u.id)});s.units=army(s);s.speed=0;return s;}

test('touch commander movement, weapon choice, aimed combat and release work on a phone-sized viewport',async({browser})=>{
 const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true});const page=await context.newPage(),s=region(),hero=army(s)[0];Object.assign(hero,{x:14,y:18,target:{x:14,y:18}});const z=makeUnit(s,'hollow',14,15);z.order='defend';z.anchor={x:14,y:15};
 try{await page.addInitScript(raw=>localStorage.setItem('kingnamic.save.v2',raw),JSON.stringify(s));await page.goto('/');await page.locator('#start').tap();await page.locator('#tab-empire').tap();await page.locator('#weapon-bow').tap();await page.locator('#hero-toggle').tap();await page.locator('#speed-1').tap();const pad=page.locator('[data-walk="-1,-1"]');await expect(pad).toBeVisible();const box=await pad.boundingBox();expect(box!.width).toBeGreaterThanOrEqual(44);expect(box!.height).toBeGreaterThanOrEqual(44);
 const cdp=await context.newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:box!.x+box!.width/2,y:box!.y+box!.height/2,id:0}]});await page.waitForTimeout(800);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});let now=await read(page),h=now.units.find((u:any)=>u.id===hero.id);expect(Math.hypot(h.x-14,h.y-18)).toBeGreaterThan(.7);const released={x:h.x,y:h.y};await page.waitForTimeout(300);h=(await read(page)).units.find((u:any)=>u.id===hero.id);expect(Math.hypot(h.x-released.x,h.y-released.y)).toBeLessThan(.3);
 const strike=await page.locator('#hero-strike').boundingBox();await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:strike!.x+strike!.width/2,y:strike!.y+strike!.height/2,id:0}]});await page.waitForTimeout(1800);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.locator('#pause').tap();now=await read(page);expect(now.units.find((u:any)=>u.id===z.id)?.hp??0).toBeLessThan(z.hp);expect(now.units.find((u:any)=>u.id===hero.id).kind).toBe('ranger');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'docs/evidence/empire-touch.png'});await writeFile('docs/evidence/empire-touch.json',JSON.stringify({fixture:true,viewport:'390x844',touch:true,physicalDevice:false,moved:released,enemyHp:now.units.find((u:any)=>u.id===z.id)?.hp??0},null,2));
 }finally{await context.close();}
});

test('regional outbreak, quarantine, timed reanimation and distant illness survive save reload',async({page})=>{
 const s=region(),dead=army(s)[1],sick=army(s)[2];dead.hp=1;infect(s,dead,'bite',74.95);plagueStep(s,.1);combatStep(s,.1);infect(s,sick,'contact',20);s.empire!.reserve.nextId=s.nextId;infect(s.empire!.reserve,s.empire!.reserve.residents![0],'supplies',25);s.nextId=Math.max(s.nextId,s.empire!.reserve.nextId);command(s,{type:'speed',speed:0});
 await page.addInitScript(raw=>{if(!localStorage.getItem('kingnamic.save.v2'))localStorage.setItem('kingnamic.save.v2',raw);},JSON.stringify(s));await page.goto('/');await page.locator('#start').click();await page.locator('#tab-people').click();await page.locator('#quarantine').click();await page.locator('#treat').click();expect((await read(page)).infection).toHaveLength(0);await page.locator('#save').click();await expect(page.locator('#save-status')).toHaveText('Saved on this device');const before=await read(page);await page.reload();await page.locator('#start').click();expect((await read(page)).corpses).toEqual(before.corpses);expect((await read(page)).empire.reserve.infection).toEqual(before.empire.reserve.infection);
 await page.locator('#speed-1').click();await expect.poll(async()=>(await read(page)).units.some((u:any)=>u.reanimatedFrom===dead.id),{timeout:14000}).toBe(true);await page.locator('#pause').click();const after=await read(page);expect(army(after).some(u=>u.id===dead.id)).toBe(false);expect(after.empire.reserve.infection).toEqual(before.empire.reserve.infection);await page.locator('#save').click();await page.reload();await page.locator('#start').click();expect((await read(page)).units).toEqual(after.units);
});

for(const weapon of ['sword','spear'] as const)test('direct '+weapon+' input damages an actual infected and preserves wounded health on switching',async({page})=>{
 const s=region(),hero=army(s)[0];Object.assign(hero,{x:14,y:15,target:{x:14,y:15},hp:100});const z=makeUnit(s,'hollow',weapon==='sword'?14.9:15.9,15);z.order='hold';
 await page.addInitScript(raw=>localStorage.setItem('kingnamic.save.v2',raw),JSON.stringify(s));await page.goto('/');await page.locator('#start').click();await page.locator('#tab-empire').click();await page.locator('#hero-toggle').click();await page.keyboard.press(weapon==='sword'?'1':'2');expect((await read(page)).commander.weapon).toBe(weapon);expect((await read(page)).units.find((u:any)=>u.id===hero.id).hp).toBe(100);
 await page.waitForTimeout(200);const point=await page.evaluate(p=>(window as any).__KINGNAMIC__.scene.screenPoint(p),z),box=await page.locator('#world canvas').boundingBox();await page.mouse.move(box!.x+point.x,box!.y+point.y);await page.locator('#speed-1').click();await page.keyboard.down('f');await expect.poll(async()=>(await read(page)).units.find((u:any)=>u.id===z.id)?.hp??0).toBeLessThan(z.hp);await page.keyboard.up('f');await page.locator('#pause').click();const struck=await read(page);expect(struck.units.find((u:any)=>u.id===z.id)?.commanderCredit===true||struck.commander.xp>0).toBe(true);
});
