import {test,expect} from '@playwright/test';
import {newGame,army,makeBuilding,makeUnit} from '../../src/game/state';
import {command} from '../../src/game/commands';
import {infect} from '../../src/game/disease';
const read=(p:any)=>p.evaluate(()=>JSON.parse(JSON.stringify((window as any).__KINGNAMIC__.runtime.state)));
function march(){const s=newGame();command(s,{type:'commander-appoint'});for(const u of army(s))Object.assign(u,{x:14,y:24});command(s,{type:'travel',ids:army(s).map(u=>u.id)});s.units=army(s);s.resources.wood=500;s.resources.stone=500;command(s,{type:'build',kind:'hearth',x:16,y:21});command(s,{type:'speed',speed:0});return s;}

test('eastern incursion warning persists and disables unsafe departure until the arriving threat clears',async({page})=>{
 const s=march();s.march!.incursion=89.8;
 await page.addInitScript(raw=>{if(!localStorage.getItem('kingnamic.save.v2'))localStorage.setItem('kingnamic.save.v2',raw);},JSON.stringify(s));await page.goto('/');await page.locator('#start').click();await page.locator('#speed-1').click();await expect(page.locator('#alert-banner')).toContainText('Eastern incursion');await page.locator('#pause').click();await page.locator('#tab-empire').click();await expect(page.locator('#travel-region')).toBeDisabled();await page.locator('#save').click();const before=await read(page);await page.reload();await page.locator('#start').click();expect((await read(page)).march.warning).toBe(before.march.warning);await page.locator('#speed-1').click();await expect.poll(async()=>(await read(page)).units.filter((u:any)=>['hollow','runner'].includes(u.kind)).length,{timeout:14000}).toBe(4);await page.locator('#pause').click();await page.screenshot({path:'docs/evidence/empire-incursion.png'});
});

test('a fallen directly controlled commander releases controls and stays dead across reload',async({page})=>{
 const s=march(),hero=army(s)[0];hero.hp=1;infect(s,hero,'bite',74.5);command(s,{type:'speed',speed:0});
 await page.addInitScript(raw=>{if(!localStorage.getItem('kingnamic.save.v2'))localStorage.setItem('kingnamic.save.v2',raw);},JSON.stringify(s));await page.goto('/');await page.locator('#start').click();
 // Start with a healthy direct-control body, then apply the explicit terminal test injury.
 await page.evaluate(()=>{const rt=(window as any).__KINGNAMIC__.runtime;rt.heroMode=true;rt.onChange();});await page.locator('#speed-1').click();await expect.poll(async()=>(await read(page)).units.some((u:any)=>u.id===hero.id)).toBe(false);await expect(page.locator('#hero-pad')).toBeHidden();await page.locator('#pause').click();await page.locator('#save').click();await page.reload();await page.locator('#start').click();expect((await read(page)).units.some((u:any)=>u.id===hero.id)).toBe(false);await page.locator('#tab-empire').click();await page.locator('#appoint-commander').click();expect((await read(page)).commander.id).not.toBe(hero.id);expect(army(await read(page))).toHaveLength(2);
});

test('secured March touch placement explains invalid river terrain and charges one valid construction',async({browser})=>{
 const s=march(),context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),page=await context.newPage();
 try{await page.addInitScript(raw=>localStorage.setItem('kingnamic.save.v2',raw),JSON.stringify(s));await page.goto('/');await page.locator('#start').tap();await page.locator('#build-farm').tap();const tap=async(x:number,y:number)=>{await page.evaluate(p=>(window as any).__KINGNAMIC__.scene.focus(p),{x,y});await page.waitForTimeout(450);const pt=await page.evaluate(p=>(window as any).__KINGNAMIC__.scene.screenPoint(p),{x,y}),box=await page.locator('#world canvas').boundingBox();await page.touchscreen.tap(box!.x+pt.x,box!.y+pt.y);};
 await tap(8,20);await expect(page.locator('#placement-bar')).toContainText('river');await expect(page.locator('#confirm-placement')).toBeDisabled();expect((await read(page)).resources.wood).toBe(s.resources.wood);await tap(18,20);await expect(page.locator('#confirm-placement')).toBeEnabled();const confirm=await page.locator('#confirm-placement').boundingBox();expect(confirm).not.toBeNull();expect(confirm!.y).toBeGreaterThanOrEqual(0);expect(confirm!.y+confirm!.height).toBeLessThanOrEqual(844);expect(await page.evaluate(({x,y})=>document.elementFromPoint(x,y)?.closest('#confirm-placement')?.id,{x:confirm!.x+confirm!.width/2,y:confirm!.y+confirm!.height/2})).toBe('confirm-placement');await page.touchscreen.tap(confirm!.x+confirm!.width/2,confirm!.y+confirm!.height/2);await expect.poll(async()=>(await read(page)).buildings.filter((b:any)=>b.kind==='farm').length).toBe(1);expect((await read(page)).resources.wood).toBe(s.resources.wood-40);await page.screenshot({path:'docs/evidence/empire-touch-building.png'});
 }finally{await context.close();}
});

test('complete March wipe returns command home, preserves fallen company and permits paid rebuilding',async({page})=>{
 const s=march(),ids=army(s).map(u=>u.id);for(const u of army(s)){u.hp=1;infect(s,u,'bite',74.5);}command(s,{type:'speed',speed:0});
 await page.addInitScript(raw=>{if(!localStorage.getItem('kingnamic.save.v2'))localStorage.setItem('kingnamic.save.v2',raw);},JSON.stringify(s));await page.goto('/');await page.locator('#start').click();await page.locator('#speed-1').click();await expect.poll(async()=>army(await read(page)).length).toBe(0);await page.locator('#pause').click();const fallen=await read(page);await page.locator('#tab-empire').click();await page.locator('#home-watch').click();expect((await read(page)).region).toBeUndefined();expect(army(await read(page))).toHaveLength(0);expect((await read(page)).empire.reserve.corpses).toEqual(fallen.corpses);expect((await read(page)).empire.reserve.buildings).toEqual(fallen.buildings);
 await page.locator('#tab-army').click();await page.locator('#army-recruit').click();const before=await read(page);await page.locator('#recruit-warden').click();const rebuilt=await read(page);expect(army(rebuilt)).toHaveLength(1);expect(ids.includes(army(rebuilt)[0].id)).toBe(false);expect(rebuilt.resources.stone).toBe(before.resources.stone-20);await page.locator('#tab-empire').click();await page.locator('#appoint-commander').click();await page.locator('#save').click();await expect(page.locator('#save-status')).toHaveText('Saved on this device');await page.reload();await page.locator('#start').click();expect(army(await read(page))).toHaveLength(1);expect((await read(page)).empire.reserve.corpses).toEqual(fallen.corpses);
});
