import {test,expect,type Page} from '@playwright/test';
import {writeFile} from 'node:fs/promises';
export const read=(p:Page)=>p.evaluate(()=>JSON.parse(JSON.stringify((window as any).__KINGNAMIC__.runtime.state)));
const friendly=(s:any)=>s.units.filter((u:any)=>['warden','ranger','spearman','scout'].includes(u.kind));
const foes=(s:any)=>s.units.filter((u:any)=>['hollow','runner','brute'].includes(u.kind));
async function pause(p:Page){if((await read(p)).speed)await p.locator('#pause').click();}
async function focus(p:Page,x:number,y:number){await p.evaluate(p=>(window as any).__KINGNAMIC__.scene.focus(p),{x,y});await p.waitForTimeout(450);}
async function tile(p:Page,x:number,y:number){const pt=await p.evaluate(p=>(window as any).__KINGNAMIC__.scene.screenPoint(p),{x,y});await p.locator('#world canvas').click({position:pt});}
async function select(p:Page,ids:number[]){await p.locator('#tab-army').click();await p.locator('#army-orders').click();await p.locator('#select-none').click();await p.locator('#army-roster').click();for(const id of ids)await p.locator('#unit-'+id).click();}
async function order(p:Page,ids:number[],name:string,x?:number,y?:number){await select(p,ids);await p.locator('#army-orders').click();await p.locator('#order-'+name).click();if(x!==undefined){await focus(p,x,y!);await tile(p,x,y!);}}
async function waitMove(p:Page,id:number,x:number,y:number){await expect.poll(async()=>{const u=friendly(await read(p)).find((u:any)=>u.id===id);return u?Math.hypot(u.x-x,u.y-y):999;},{timeout:25000}).toBeLessThan(1.4);}

test('fresh kingdom explores, clears, founds, freely builds, stations defenders and returns with exact progress',async({page})=>{
 test.setTimeout(240000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await page.locator('#start').click();await pause(page);
 await page.locator('#tab-army').click();await page.locator('#army-recruit').click();await page.locator('#recruit-warden').click();await page.locator('#recruit-ranger').click();
 const starting=await read(page),all=friendly(starting),company=[all[0].id,all[1].id,all[2].id],guards=all.slice(3).map((u:any)=>u.id);
 await order(page,guards,'defend',14,17);await select(page,company);await page.locator('#tab-empire').click();await page.locator('#appoint-commander').click();await expect(page.locator('#travel-region')).toBeDisabled();await page.locator('#gather-road').click();await page.locator('#speed-2').click();await expect(page.locator('#travel-region')).toBeEnabled({timeout:25000});await page.locator('#travel-region').click();
 let s=await read(page);expect(s.region).toBe('march');expect(s.speed).toBe(0);expect(friendly(s).map((u:any)=>u.id).sort()).toEqual([...company].sort());expect(friendly(s.empire.reserve).map((u:any)=>u.id).sort()).toEqual([...guards].sort());expect(friendly(s.empire.reserve).every((u:any)=>u.order==='defend')).toBe(true);const terrain=await page.evaluate(async()=>{const {iso}=await import('/src/render/art.ts' as string),{MAP_W,MAP_H}=await import('/src/game/config.ts' as string),image=(window as any).__KINGNAMIC__.scene.textures.get('valley').getSourceImage(),corners=[iso(0,0),iso(MAP_W-1,0),iso(0,MAP_H-1),iso(MAP_W-1,MAP_H-1)];return {width:image.width,height:image.height,minX:Math.min(...corners.map((p:any)=>p.x-32)),maxX:Math.max(...corners.map((p:any)=>p.x+32)),maxY:Math.max(...corners.map((p:any)=>p.y+16))};});expect(terrain.minX).toBeGreaterThanOrEqual(0);expect(terrain.maxX).toBeLessThanOrEqual(terrain.width);expect(terrain.maxY).toBeLessThanOrEqual(terrain.height);
 await page.screenshot({path:'docs/evidence/empire-arrival.png'});await page.locator('#save').click();expect(await page.locator('#save-status').textContent()).not.toContain('unavailable');await page.reload();await page.locator('#start').click();await pause(page);expect((await read(page)).region).toBe('march');
 // Real tactical inputs first: escorting swords hold the approach while the commander shoots.
 const hero=s.commander.id;await order(page,company.filter(id=>id!==hero),'hunt',14,14);await order(page,[hero],'move',14,17);await page.locator('#tab-empire').click();await page.locator('#weapon-bow').click();await page.locator('#hero-toggle').click();await page.locator('#speed-2').click();
 await page.keyboard.down('f');
 const combatStart=Date.now();while(Date.now()-combatStart<60000){s=await read(page);if(!foes(s).length||!friendly(s).some((u:any)=>u.id===hero))break;const h=friendly(s).find((u:any)=>u.id===hero),z=foes(s).sort((a:any,b:any)=>Math.hypot(a.x-h.x,a.y-h.y)-Math.hypot(b.x-h.x,b.y-h.y))[0];const pt=await page.evaluate(p=>(window as any).__KINGNAMIC__.scene.screenPoint(p),z);const box=await page.locator('#world canvas').boundingBox();await page.mouse.move(box!.x+Math.max(10,Math.min(box!.width-10,pt.x)),box!.y+Math.max(10,Math.min(box!.height-10,pt.y)));if(s.infection.some((i:any)=>i.personId===hero)){await page.keyboard.up('f');await page.locator('#pause').click();await page.locator('#tab-people').click();const treat=page.locator('#treat');if(await treat.count()&&await treat.isEnabled())await treat.click();await page.keyboard.down('f');await page.locator('#speed-2').click();}await page.waitForTimeout(250);}
 await page.keyboard.up('f');await pause(page);s=await read(page);expect(foes(s)).toHaveLength(0);expect(friendly(s).length).toBeGreaterThanOrEqual(2);expect(friendly(s).some((u:any)=>u.id===hero)).toBe(true);await page.keyboard.press('Escape');await page.screenshot({path:'docs/evidence/empire-combat.png'});await writeFile('docs/evidence/empire-first-combat.json',JSON.stringify({region:s.region,weapon:s.commander.weapon,commander:{id:hero,hp:friendly(s).find((u:any)=>u.id===hero)?.hp,xp:s.commander.xp},remainingThreats:foes(s).length,company:friendly(s).map((u:any)=>({id:u.id,kind:u.kind,hp:u.hp})),discoveries:s.march.seen},null,2));
 // Visit all landmarks with genuine move orders; no coordinates or rewards are injected.
 for(const [x,y]of [[14,12],[5,14],[21,10]]){await order(page,[hero],'move',x,y);await page.locator('#speed-2').click();await waitMove(page,hero,x,y);await pause(page);}
 expect((await read(page)).march.seen).toHaveLength(3);
 await order(page,[hero],'move',16,20);await page.locator('#speed-2').click();await waitMove(page,hero,16,20);await pause(page);await page.locator('#tab-empire').click();await page.locator('#place-outpost').click();await focus(page,17,19);await tile(page,17,19);
 s=await read(page);expect(s.march.secured).toBe(true);expect(s.population).toBe(2);const founders=s.residents.map((r:any)=>r.id);expect(founders.every((id:number)=>starting.residents.some((r:any)=>r.id===id))).toBe(true);const hearth=s.buildings.find((b:any)=>b.kind==='hearth');await page.locator(`#settlement-name-${hearth.id}`).fill('Splitwater Refuge');await page.locator(`[data-rename-settlement="${hearth.id}"]`).click();expect((await read(page)).buildings.find((b:any)=>b.id===hearth.id).name).toBe('Splitwater Refuge');
 await page.locator('#outpost-build').click();await page.locator('#category-settlement').click();await page.locator('#build-farm').click();await tile(page,18,19);await page.keyboard.press('Escape');await page.locator('#speed-2').click();await expect.poll(async()=>(await read(page)).buildings.find((b:any)=>b.kind==='farm')?.progress,{timeout:25000}).toBe(1);await pause(page);
 await page.locator('#tab-people').click();await page.locator('#job-builders-minus').click();await page.locator('#job-farmers-plus').click();expect((await read(page)).jobs.farmers).toBe(1);s=await read(page);const defenders=friendly(s).filter((u:any)=>u.id!==hero).map((u:any)=>u.id);await order(page,defenders,'defend',16,18);await select(page,[hero]);await page.locator('#tab-empire').click();await page.locator('#gather-road').click();await page.locator('#speed-2').click();await expect(page.locator('#travel-region')).toBeEnabled({timeout:25000});await pause(page);const outpost=await read(page),crowns=outpost.resources.stone;await page.screenshot({path:'docs/evidence/empire-outpost.png'});await page.locator('#travel-region').click();
 expect((await read(page)).region).toBeUndefined();await page.locator('#save').click();await page.reload();await page.locator('#start').click();await pause(page);await page.locator('#tab-empire').click();await expect(page.locator('#travel-region')).toBeEnabled();await page.locator('#travel-region').click();s=await read(page);
 expect(s.buildings).toEqual(outpost.buildings);expect(s.resources.stone).toBe(crowns);expect(s.march.rewarded).toBe(true);expect(s.march.seen).toHaveLength(3);expect(friendly(s).filter((u:any)=>defenders.includes(u.id)).every((u:any)=>u.order==='defend')).toBe(true);expect(s.residents).toEqual(outpost.residents);expect(s.infection).toEqual(outpost.infection);expect(errors).toEqual([]);
 await page.locator('#save').click();await writeFile('docs/evidence/empire-journey.json',JSON.stringify({fresh:true,fixture:false,company,guards,defenders,founders,errors,returnRoundtrip:{region:s.region,settlements:s.buildings.filter((b:any)=>b.kind==='hearth').map((b:any)=>({name:b.name,x:b.x,y:b.y})),buildings:s.buildings.filter((b:any)=>b.kind!=='hearth').map((b:any)=>({kind:b.kind,x:b.x,y:b.y,progress:b.progress})),discovered:s.march.seen,rescued:s.march.rescued,rewarded:s.march.rewarded,guardOrders:s.units.filter((u:any)=>defenders.includes(u.id)).map((u:any)=>({id:u.id,order:u.order})),population:s.population,resources:s.resources,infections:s.infection.length}},null,2));
});
