import {test,expect,type Page} from '@playwright/test';
import {writeFile} from 'node:fs/promises';
import {newGame,army,makeBuilding} from '../../src/game/state';
import {addResidents} from '../../src/game/population';
import {command} from '../../src/game/commands';
import {decode} from '../../src/game/persistence';
import type {SoldierKind} from '../../src/game/types';
if(process.env.KINGNAMIC_HARDWARE_PROFILE==='1')test.use({launchOptions:{args:['--enable-gpu','--use-gl=angle','--use-angle=d3d11']}});

const read=(page:Page)=>page.evaluate(()=>JSON.parse(JSON.stringify((window as any).__KINGNAMIC__.runtime.state)));
const foes=(s:any)=>s.units.filter((u:any)=>['hollow','runner','brute'].includes(u.kind));
async function focus(page:Page,p:{x:number;y:number}){await page.evaluate(p=>(window as any).__KINGNAMIC__.scene.focus(p),p);await page.waitForTimeout(350);}
async function moveClass(page:Page,kind:SoldierKind,point:{x:number;y:number}){await page.locator('#tab-army').click();await page.locator('#army-class-select').selectOption(kind);await page.locator('#order-move').click();await focus(page,point);const p=await page.evaluate(p=>(window as any).__KINGNAMIC__.scene.screenPoint(p),point);await page.locator('#world canvas').click({position:p});}
async function clearGateAim(page:Page,id:number){return page.evaluate(async id=>{const {uniso}=await import('/src/render/art.ts' as string),rt=(window as any).__KINGNAMIC__.runtime,scene=(window as any).__KINGNAMIC__.scene,s=rt.world,gate=s.buildings.find((b:any)=>b.id===id);if(!gate)return null;const q=scene.screenPoint(gate),cam=scene.cameras.main,rivals=s.buildings.filter((b:any)=>b.owner==='rival').sort((a:any,b:any)=>b.x+b.y-a.x-a.y),hit=(p:{x:number;y:number})=>{const structure=rivals.find((b:any)=>{const screen=scene.screenPoint(b);return Math.abs(p.x-screen.x)<28&&p.y<screen.y+12&&p.y>screen.y-(b.kind==='hearth'||b.kind==='tower'?90:b.kind==='wall'||b.kind==='gate'?30:58);});if(structure)return structure;const world=cam.getWorldPoint(p.x,p.y),tile=uniso(world.x,world.y);return rivals.find((b:any)=>b.x===Math.round(tile.x)&&b.y===Math.round(tile.y));};for(let dy=-28;dy<=10;dy+=2)for(let dx=-26;dx<=26;dx+=2){const p={x:q.x+dx,y:q.y+dy};if(hit(p)?.id===id)return p;}return null;},id);}

const forceSize=Number(process.env.MOSSGATE_TEST_FORCE??100);if(![25,50,75,100].includes(forceSize))throw Error(`Unsupported Mossgate test force: ${forceSize}`);
test(forceSize===100?'a prepared 100-soldier company naturally breaches and captures Mossgate without battle-state edits':`a live ${forceSize}-soldier company siege is profiled in Chrome`,async({page})=>{
 test.setTimeout(600000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 const s=newGame(91572);s.speed=0;s.resources={wood:1200,stone:3200,food:8000,herbs:100};
 const barracks=s.buildings.find(b=>b.kind==='barracks')!;barracks.level=3;makeBuilding(s,'barracks',18,9,true);makeBuilding(s,'barracks',20,10,true);
 addResidents(s,110);
 const wardenTotal=Math.round(forceSize*.39),spearmanTotal=Math.round(forceSize*.25),rangerTotal=Math.round(forceSize*.21),scoutTotal=forceSize-wardenTotal-spearmanTotal-rangerTotal;
 const recruitment:[SoldierKind,number][]=[['warden',wardenTotal-2],['spearman',spearmanTotal],['ranger',rangerTotal-1],['scout',scoutTotal]],recruitmentResults=[] as string[];
 for(const [kind,count]of recruitment){const r=command(s,{type:'recruit',kind,count});if(!r.ok)throw Error(`Prepared save could not recruit ${count} ${kind}: ${r.message}`);recruitmentResults.push(r.message);}
 const force=army(s);expect(force).toHaveLength(forceSize);expect(force.filter(u=>u.kind==='warden'||u.kind==='spearman').length).toBeGreaterThan(forceSize*.6);
 const commander=force.find(u=>u.kind==='warden')!;expect(command(s,{type:'commander-appoint',id:commander.id}).ok).toBe(true);
 const companyIds=force.map(u=>u.id),decoded=decode(JSON.stringify(s));if(!decoded)throw Error('Prepared 100-soldier save failed decode before browser load.');
 // Seed exactly once. addInitScript reruns after every navigation and would
 // overwrite the captured campaign with this prepared save during reload QA.
 await page.goto('/');await page.bringToFront();await page.evaluate(raw=>localStorage.setItem('kingnamic.save.v2',raw),JSON.stringify(s));await page.reload();const persisted=await page.evaluate(async()=>{const raw=localStorage.getItem('kingnamic.save.v2'),{decode}=await import('/src/game/persistence.ts' as string),loaded=raw?decode(raw):null;return loaded?.units.length??null;});expect(persisted).toBe(forceSize);await page.locator('#start').click();expect((await read(page)).units.filter((u:any)=>['warden','spearman','ranger','scout'].includes(u.kind))).toHaveLength(forceSize);
 await page.locator('#tab-army').click();await page.locator('#select-all').click();await page.locator('#tab-empire').click();await page.locator('#gather-road').click();
 await page.locator('#speed-2').click();await expect(page.locator('#travel-region')).toBeEnabled({timeout:90000});await page.locator('#travel-region').click();let state=await read(page);expect(state.region).toBe('march');expect(state.units.filter((u:any)=>companyIds.includes(u.id))).toHaveLength(forceSize);
 await page.locator('#tab-army').click();await page.locator('#select-all').click();await page.locator('#formation-protected').click();
 // Deploy by role so the screen, breach force and flank do not bottleneck on
 // one click point. Orders are independent and remain paused until issued.
 const approach:{kind:SoldierKind;point:{x:number;y:number}}[]=[{kind:'warden',point:{x:42,y:29}},{kind:'spearman',point:{x:42,y:31}},{kind:'ranger',point:{x:40,y:26}},{kind:'scout',point:{x:40,y:32}}];
 await page.evaluate(()=>{const rt=(window as any).__KINGNAMIC__.runtime,original=rt.orderAt,calls:any[]=[];rt.orderAt=function(...args:any[]){const start=performance.now();try{return original.apply(this,args);}finally{calls.push({selected:this.selectedIds.length,durationMs:performance.now()-start});}};(window as any).__mossgateOrderAt={original,calls};});
 for(const role of approach)if(force.some(u=>u.kind===role.kind))await moveClass(page,role.kind,role.point);
 const navigationFormation=await page.evaluate(async(ids:number[])=>{const rt=(window as any).__KINGNAMIC__.runtime,hook=(window as any).__mossgateOrderAt,{formationSlots}=await import('/src/game/army.ts' as string),troops=rt.world.units.filter((u:any)=>ids.includes(u.id)),samples:number[]=[];for(let i=0;i<25;i++){const start=performance.now();formationSlots(rt.world,troops,{x:42,y:30},{x:1,y:0});samples.push(performance.now()-start);}samples.sort((a,b)=>a-b);rt.orderAt=hook.original;return{liveGroupOrders:hook.calls,formationLayout:{soldiers:troops.length,samples:samples.length,medianMs:Number((samples[Math.floor(samples.length*.5)]??0).toFixed(3)),p95Ms:Number((samples[Math.floor(samples.length*.95)]??0).toFixed(3)),maxMs:Number((samples.at(-1)??0).toFixed(3))}};},companyIds);
 const advanced=await read(page);for(const role of approach){const group=advanced.units.filter((u:any)=>companyIds.includes(u.id)&&u.kind===role.kind);expect(group.filter((u:any)=>u.order==='move').length).toBe(group.length);}
 await page.locator('#speed-2').click();
 try {
  await expect.poll(async()=>((await read(page)).march.rival.status==='occupied'),{timeout:90000,intervals:[500,1000,2000]}).toBe(true);
 } catch(error) {
  state=await read(page);const hero=state.units.find((u:any)=>u.id===state.commander.id),nearest=state.units.filter((u:any)=>companyIds.includes(u.id)).slice(0,12).map((u:any)=>({x:u.x,y:u.y,order:u.order,target:u.target,path:u.path.slice(0,3)})),hostiles=foes(state).map((u:any)=>({kind:u.kind,x:u.x,y:u.y})),selected=await page.evaluate(()=>(window as any).__KINGNAMIC__.runtime.selectedIds.length);
  throw new Error(`Mossgate did not reveal: ${JSON.stringify({hero,nearest,hostiles,remaining:state.march.rival.remaining,selected})}; ${String(error)}`);
 }
 await page.locator('#pause').click();state=await read(page);let hero=state.units.find((u:any)=>u.id===state.commander.id);const war=state.march.rival;expect(hero).toBeTruthy();expect(war.remaining+war.casualties).toBe(100);expect(war.reserve).toBeLessThanOrEqual(80);expect(foes(state).length).toBeGreaterThan(0);
 await page.locator('#tab-army').click();await page.locator('#select-all').click();await page.locator('#army-orders').click();await page.locator('#army-roster').click();await page.locator('#unit-'+commander.id).click();await page.locator('#army-orders').click();expect(await page.evaluate(()=>(window as any).__KINGNAMIC__.runtime.selectedIds.length)).toBeGreaterThan(forceSize*.7);await page.locator('#order-hold').click();expect((await read(page)).units.filter((u:any)=>companyIds.includes(u.id)&&u.id!==commander.id&&u.order==='hold').length).toBeGreaterThan(forceSize*.7);
 await page.locator('#select-none').click();await page.locator('#army-roster').click();await page.locator('#unit-'+commander.id).click();await page.locator('#army-orders').click();await page.locator('#order-move').click();await focus(page,{x:42,y:29});const point=await page.evaluate(p=>(window as any).__KINGNAMIC__.scene.screenPoint(p),{x:42,y:29});await page.locator('#world canvas').click({position:point});let commandState=await read(page);expect(commandState.units.find((u:any)=>u.id===commander.id)?.order,'Captain Move order must be accepted while the rest hold.').toBe('move');await page.locator('#speed-2').click();try{await expect.poll(async()=>{const s=await read(page),h=s.units.find((u:any)=>u.id===commander.id);return h&&Math.hypot(h.x-47,h.y-29)<5.5;},{timeout:30000}).toBe(true);}catch(error){const detail=await page.evaluate(async id=>{const rt=(window as any).__KINGNAMIC__.runtime,s=rt.world,u=s.units.find((v:any)=>v.id===id),{movementBlocker,navigation}=await import('/src/game/navigation.ts' as string),nav=navigation(s),next=u?.path[0],block=next&&movementBlocker(nav,u,next,false,true,'player');return{hero:u&&{x:u.x,y:u.y,hp:u.hp,order:u.order,target:u.target,anchor:u.anchor,path:u.path.slice(0,8),repath:u.repath},gateDistance:u&&Math.hypot(u.x-47,u.y-29),next,nextBlock:block==='terrain'?'terrain':block?.kind??null,nextTile:next&&(await import('/src/game/map.ts' as string)).tileAt(next.x,next.y,s)?.terrain,selected:rt.selectedIds,speed:s.speed,message:rt.message,nearby:s.units.filter((v:any)=>v.id!==id&&['warden','ranger','spearman','scout'].includes(v.kind)&&Math.hypot(v.x-u.x,v.y-u.y)<1.2).slice(0,16).map((v:any)=>({id:v.id,x:v.x,y:v.y,order:v.order,target:v.target,path:v.path.slice(0,2)}))};},commander.id);throw new Error(`Commander did not reach capture range: ${JSON.stringify(detail)}; ${String(error)}`);}await page.locator('#pause').click();state=await read(page);hero=state.units.find((u:any)=>u.id===state.commander.id);expect(hero).toBeTruthy();
 await page.locator('#tab-army').click();await page.locator('#select-all').click();await page.locator('#army-orders').click();await page.locator('#order-attack').click();await focus(page,{x:47,y:29});
 const gate=state.buildings.find((b:any)=>b.kind==='gate'&&b.owner==='rival');expect(gate).toBeTruthy();const canvas=page.locator('#world canvas'),box=await canvas.boundingBox(),pt=await clearGateAim(page,gate.id);if(!box)throw Error('World canvas unavailable');expect(pt,'Find an unobstructed point on the visible gate hit area.').not.toBeNull();await page.mouse.click(box.x+pt!.x,box.y+pt!.y,{button:'right'});
 await expect.poll(async()=>{const s=await read(page);return s.units.filter((u:any)=>companyIds.includes(u.id)&&u.order==='attack').length;},{timeout:10000}).toBeGreaterThan(0);
 await expect.poll(async()=>{const s=await read(page);return s.units.filter((u:any)=>companyIds.includes(u.id)&&u.order==='attack'&&u.focus===gate.id).length;},{timeout:10000}).toBeGreaterThan(0);
 await page.screenshot({path:forceSize===100?'docs/evidence/mossgate-natural-siege-start.png':`docs/evidence/mossgate-force-${forceSize}-battle.png`});await page.locator('#speed-2').click();
 const perf={...await page.evaluate(async()=>{const rt=(window as any).__KINGNAMIC__.runtime,tick=rt.tick,counts=()=>({activeUnits:rt.world.units.length,playerSoldiers:rt.world.units.filter((u:any)=>!u.faction&&['warden','spearman','ranger','scout'].includes(u.kind)).length,rivalSoldiers:rt.world.units.filter((u:any)=>u.faction==='rival').length,infected:rt.world.units.filter((u:any)=>['hollow','runner','brute'].includes(u.kind)).length,remaining:rt.world.march?.rival?.remaining,reserve:rt.world.march?.rival?.reserve});const atStart=counts(),canvas=(window as any).__KINGNAMIC__.game.canvas,gl:any=canvas.getContext('webgl2')??canvas.getContext('webgl'),debug=gl?.getExtension('WEBGL_debug_renderer_info'),renderer={type:(window as any).__KINGNAMIC__.game.renderer.type,vendor:gl?.getParameter(debug?debug.UNMASKED_VENDOR_WEBGL:gl.VENDOR),device:gl?.getParameter(debug?debug.UNMASKED_RENDERER_WEBGL:gl.RENDERER)};let frames=0,tickMs=0;const samples:number[]=[],obs=typeof PerformanceObserver==='undefined'?undefined:new PerformanceObserver((l:any)=>samples.push(...l.getEntries().map((e:any)=>e.duration)));obs?.observe({entryTypes:['longtask']});rt.tick=function(delta:number){const t=performance.now(),r=tick.call(this,delta);tickMs+=performance.now()-t;return r;};const start=performance.now(),times:number[]=[];await new Promise<void>(resolve=>{let prev=start;const frame=(now:number)=>{times.push(now-prev);prev=now;frames++;if(now-start<5000)requestAnimationFrame(frame);else resolve();};requestAnimationFrame(frame);});rt.tick=tick;obs?.disconnect();times.sort((a,b)=>a-b);return{wallMs:Math.round(performance.now()-start),frames,fps:Math.round(frames*1000/(performance.now()-start)),medianFrameMs:Number((times[Math.floor(times.length*.5)]??0).toFixed(2)),p95FrameMs:Number((times[Math.floor(times.length*.95)]??0).toFixed(2)),worstFrameMs:Number((times.at(-1)??0).toFixed(2)),runtimeTickMs:Number(tickMs.toFixed(1)),longTasks:samples,atStart:atStart,atEnd:counts(),renderer,browser:{visibility:document.visibilityState,focused:document.hasFocus(),devicePixelRatio}};}),navigationFormation};
 if(forceSize<100){await page.locator('#pause').click();state=await read(page);expect(state.march.rival.status).toBe('occupied');const playerSurvivors=state.units.filter((u:any)=>companyIds.includes(u.id)&&u.hp>0).length;expect(state.stats.lost+playerSurvivors).toBeGreaterThan(0);await page.screenshot({path:`docs/evidence/mossgate-force-${forceSize}-profiled.png`});await writeFile(`docs/evidence/mossgate-force-${forceSize}.json`,JSON.stringify({forceSize,fixture:'Only mature home economy and garrison infrastructure were prepared. All soldiers were recruited with normal command eligibility and costs; departure, positioning, gate targeting and the measured combat simulation were live. This run profiles an opening engagement only and makes no full-capture claim.',forceComposition:force.map(u=>u.kind),performance:perf,afterWindow:{casualties:state.march.rival.casualties,remaining:state.march.rival.remaining,reserve:state.march.rival.reserve,playerLost:state.stats.lost,playerSurvivors,playerDefeated:playerSurvivors===0,gateHp:state.buildings.find((b:any)=>b.id===gate.id)?.hp,infected:foes(state).length,errors}},null,2));return;}
 await page.locator('#tab-empire').click();const started=Date.now(),history:any[]=[];let nextLog=started+10000,cleanupHunt=false;
 while(Date.now()-started<420000){
  await page.waitForTimeout(2500);state=await read(page);const r=state.march.rival,hero=state.units.find((u:any)=>u.id===state.commander.id);history.push({elapsedMs:Date.now()-started,remaining:r.remaining,reserve:r.reserve,activeRivals:state.units.filter((u:any)=>u.faction==='rival').length,playerArmy:state.units.filter((u:any)=>companyIds.includes(u.id)).length,lost:state.stats.lost,slain:state.stats.slain,infected:foes(state).length,heroHp:hero?.hp,gateHp:state.buildings.find((b:any)=>b.id===gate.id)?.hp,warning:r.warning});
  if(Date.now()>=nextLog){console.log('Mossgate live siege',JSON.stringify(history.at(-1)));nextLog+=15000;}
  if(await page.locator('#capture-stronghold').count()&&await page.locator('#capture-stronghold').isEnabled())break;
  if(!cleanupHunt&&r.remaining===0&&r.reserve===0&&!state.units.some((u:any)=>u.faction==='rival')){
   const liveThreats=foes(state);await page.locator('#pause').click();await page.locator('#tab-army').click();await page.locator('#select-all').click();await page.locator('#army-orders').click();await page.locator('#order-hunt').click();
   if(liveThreats.length){const target={x:liveThreats[0].x,y:liveThreats[0].y};await focus(page,target);const huntPoint=await page.evaluate(p=>(window as any).__KINGNAMIC__.scene.screenPoint(p),target);await page.locator('#world canvas').click({position:huntPoint});const ordered=await read(page);expect(ordered.units.filter((u:any)=>companyIds.includes(u.id)&&u.order==='hunt').length).toBeGreaterThan(0);await page.locator('#speed-2').click();await expect.poll(async()=>foes(await read(page)).length,{timeout:90000}).toBe(0);await page.locator('#pause').click();}cleanupHunt=true;await page.locator('#tab-empire').click();await page.locator('#speed-2').click();
  }
 }
 expect(await page.locator('#capture-stronghold').isEnabled(),`Siege did not open capture after live combat: ${JSON.stringify(history.at(-1))}`).toBe(true);if((await read(page)).speed)await page.locator('#pause').click();await expect(page.locator('#capture-stronghold')).toBeEnabled();
 await page.screenshot({path:'docs/evidence/mossgate-natural-siege-won.png'});await page.locator('#capture-stronghold').click();state=await read(page);
 expect(state.march.rival.status).toBe('captured');expect(state.march.secured).toBe(true);expect(state.buildings.find((b:any)=>b.name==='Mossgate Hall').owner).toBe('player');expect(state.units.filter((u:any)=>companyIds.includes(u.id)&&u.hp>0).length).toBeGreaterThan(0);expect(errors).toEqual([]);
 const captured=await read(page),roundTrip=decode(JSON.stringify(captured));if(!roundTrip)await writeFile('docs/evidence/mossgate-captured-test-state.json',JSON.stringify(captured));expect(roundTrip,'Captured siege state must pass the same decoder used by saves.').toBeTruthy();await page.locator('#save').click();const savedStatus=await page.locator('#save-status').textContent(),storedRaw=await page.evaluate(()=>localStorage.getItem('kingnamic.save.v2')),stored=storedRaw?decode(storedRaw):null;if(!stored)await writeFile('docs/evidence/mossgate-captured-test-state.json',storedRaw??'No local save written');expect(savedStatus).toContain('Saved');expect(stored?.march?.rival?.status,'The actual offline save must retain captured Mossgate.').toBe('captured');await page.reload();await page.locator('#start').click();state=await read(page);expect(state.march.rival.status).toBe('captured');expect(state.buildings.find((b:any)=>b.name==='Mossgate Hall').owner).toBe('player');
 if(state.speed)await page.locator('#pause').click();
 const existingBuildings=state.buildings.map((b:any)=>b.id),buildSites=await page.evaluate(async()=>{const {buildError}=await import('/src/game/commands.ts' as string),s=(window as any).__KINGNAMIC__.runtime.world,h=s.buildings.find((b:any)=>b.name==='Mossgate Hall'),sites:any[]=[];for(let radius=1;radius<=12;radius++)for(let y=h.y-radius;y<=h.y+radius;y++)for(let x=h.x-radius;x<=h.x+radius;x++)if(Math.max(Math.abs(x-h.x),Math.abs(y-h.y))===radius&&!buildError(s,'cottage',x,y))sites.push({x,y});return sites;});expect(buildSites,'Captured Mossgate must permit a normal player building placement.').not.toHaveLength(0);
 await page.locator('#tab-build').click();await page.locator('#category-settlement').click();await page.locator('#build-cottage').click();await focus(page,buildSites[0]);const buildCanvas=page.locator('#world canvas'),buildBox=await buildCanvas.boundingBox();if(!buildBox)throw Error('Mossgate build canvas unavailable');let buildSite:any,buildPoint:any,previewSite:any;for(const candidate of buildSites){const point=await page.evaluate(p=>(window as any).__KINGNAMIC__.scene.screenPoint(p),candidate);if(point.x<0||point.y<0||point.x>=buildBox.width||point.y>=buildBox.height)continue;await page.mouse.move(buildBox.x+point.x,buildBox.y+point.y);await page.waitForTimeout(30);const preview=await page.evaluate(()=>{const p=(window as any).__KINGNAMIC__.scene.hoverTile;return p&&{x:p.x,y:p.y};});if(!preview)continue;const valid=await page.evaluate(async p=>{const {buildError}=await import('/src/game/commands.ts' as string),s=(window as any).__KINGNAMIC__.runtime.world;return !buildError(s,'cottage',p.x,p.y);},preview);if(valid){buildSite=candidate;buildPoint=point;previewSite=preview;break;}}expect(previewSite,'Find an unobstructed valid build-preview tile near Mossgate.').toBeTruthy();await page.mouse.click(buildBox.x+buildPoint.x,buildBox.y+buildPoint.y);state=await read(page);const addedCottage=state.buildings.find((b:any)=>b.kind==='cottage'&&!existingBuildings.includes(b.id));expect(addedCottage).toMatchObject({x:previewSite.x,y:previewSite.y});expect(addedCottage.owner).not.toBe('rival');
 await page.locator('#tab-army').click();await page.locator('#army-orders').click();await page.locator('#select-all').click();const selectedDefenders=await page.evaluate(()=>(window as any).__KINGNAMIC__.runtime.selectedIds.slice());expect(selectedDefenders.length).toBeGreaterThan(0);await page.locator('#order-defend').click();const holdPoint={x:47,y:34};await focus(page,holdPoint);const holdCanvas=page.locator('#world canvas'),holdBox=await holdCanvas.boundingBox(),holdScreen=await page.evaluate(p=>(window as any).__KINGNAMIC__.scene.screenPoint(p),holdPoint);if(!holdBox)throw Error('Mossgate defense canvas unavailable');await page.locator('#world canvas').click({position:holdScreen});state=await read(page);const stationedIds=state.units.filter((u:any)=>selectedDefenders.includes(u.id)&&u.order==='defend').map((u:any)=>u.id);expect(stationedIds.length).toBeGreaterThan(0);const assigned=new Set(state.units.filter((u:any)=>stationedIds.includes(u.id)).map((u:any)=>`${u.target.x},${u.target.y}`));expect(assigned.size).toBe(stationedIds.length);
 const beforeOrganization=await page.evaluate((ids:number[])=>{const s=(window as any).__KINGNAMIC__.runtime.world,group=s.units.filter((u:any)=>ids.includes(u.id));return{soldiers:group.length,meanDistance:group.reduce((sum:number,u:any)=>sum+Math.hypot(u.x-u.target.x,u.y-u.target.y),0)/Math.max(1,group.length)};},stationedIds);await page.locator('#speed-2').click();await page.waitForTimeout(20000);await page.locator('#pause').click();state=await read(page);const organization=await page.evaluate((ids:number[])=>{const s=(window as any).__KINGNAMIC__.runtime.world,group=s.units.filter((u:any)=>ids.includes(u.id)&&u.hp>0),distances=group.map((u:any)=>Math.hypot(u.x-u.target.x,u.y-u.target.y)).sort((a:number,b:number)=>a-b),close=distances.filter((d:number)=>d<1).length;return{soldiers:group.length,uniqueDestinations:new Set(group.map((u:any)=>`${u.target.x},${u.target.y}`)).size,atAssignedPost:close,withinOneTile:close/Math.max(1,group.length),meanDistance:Number((distances.reduce((a:number,b:number)=>a+b,0)/Math.max(1,distances.length)).toFixed(2)),maximumDistance:Number((distances.at(-1)??0).toFixed(2)),moving:group.filter((u:any)=>u.path.length).length,threats:s.units.filter((u:any)=>['hollow','runner','brute'].includes(u.kind)).length};},stationedIds);expect(organization.soldiers).toBeGreaterThan(stationedIds.length*.8);expect(organization.uniqueDestinations).toBe(organization.soldiers);expect(organization.meanDistance).toBeLessThan(beforeOrganization.meanDistance);await page.screenshot({path:'docs/evidence/mossgate-occupation.png'});
 const beforeResponse=await read(page),nearbyThreats=foes(beforeResponse),garrisonSurvivorIds=stationedIds.filter((id:number)=>state.units.some((u:any)=>u.id===id&&u.hp>0&&u.order==='defend'));let threatsClearedForTravel=nearbyThreats.length===0;
 expect(garrisonSurvivorIds.length).toBeGreaterThan(0);
 await page.locator('#save').click();expect(await page.locator('#save-status').textContent()).toContain('Saved');await page.reload();await page.locator('#start').click();state=await read(page);expect(state.march.rival.status).toBe('captured');expect(state.buildings.some((b:any)=>b.id===addedCottage.id&&b.x===previewSite.x&&b.y===previewSite.y&&b.owner!=='rival')).toBe(true);expect(garrisonSurvivorIds.every((id:number)=>state.units.find((u:any)=>u.id===id)?.order==='defend')).toBe(true);
 const ready=new Set(state.units.filter((u:any)=>companyIds.includes(u.id)&&u.hp>0&&!u.injury&&!state.infection.some((i:any)=>i.personId===u.id)).map((u:any)=>u.id));let travelIds=[state.commander.id,...[...ready].filter((id:number)=>id!==state.commander.id)].slice(0,6);expect(travelIds).toContain(state.commander.id);
 await page.locator('#tab-army').click();await page.locator('#army-orders').click();await page.locator('#select-none').click();await page.locator('#army-roster').click();for(const id of travelIds){let unit=page.locator('#unit-'+id);for(let i=0;i<Math.ceil(state.units.length/12)&&!await unit.count();i++){await expect(page.locator('#roster-next')).toBeEnabled();await page.locator('#roster-next').click();}await expect(unit).toHaveCount(1);await unit.click();}
 if(nearbyThreats.length){await page.locator('#army-orders').click();await page.locator('#order-hunt').click();const target={x:nearbyThreats[0].x,y:nearbyThreats[0].y};await focus(page,target);const targetPoint=await page.evaluate(p=>(window as any).__KINGNAMIC__.scene.screenPoint(p),target);await page.locator('#world canvas').click({position:targetPoint});await page.locator('#speed-2').click();await expect.poll(async()=>foes(await read(page)).length,{timeout:90000}).toBe(0);await page.locator('#pause').click();state=await read(page);threatsClearedForTravel=foes(state).length===0;expect(threatsClearedForTravel).toBe(true);travelIds=travelIds.filter(id=>state.units.some((u:any)=>u.id===id&&u.hp>0&&!u.injury&&!state.infection.some((i:any)=>i.personId===id)));expect(travelIds).toContain(state.commander.id);await page.locator('#army-orders').click();await page.locator('#select-none').click();await page.locator('#army-roster').click();for(const id of travelIds){let unit=page.locator('#unit-'+id);for(let i=0;i<Math.ceil(state.units.length/12)&&!await unit.count();i++){await expect(page.locator('#roster-next')).toBeEnabled();await page.locator('#roster-next').click();}await expect(unit).toHaveCount(1);await unit.click();}}
 await page.locator('#tab-empire').click();await page.locator('#gather-road').click();await page.locator('#speed-2').click();const homeward=page.locator('#travel-region');await expect(homeward).toBeEnabled({timeout:90000});await page.locator('#pause').click();await expect(homeward).toBeEnabled();await homeward.click();state=await read(page);expect(state.region).toBeUndefined();expect(state.empire.reserve.march.rival.status).toBe('captured');expect(state.empire.reserve.buildings.some((b:any)=>b.id===addedCottage.id&&b.owner!=='rival')).toBe(true);const parkedGarrison=state.empire.reserve.units.filter((u:any)=>stationedIds.includes(u.id)&&!travelIds.includes(u.id)&&u.hp>0&&Math.hypot(u.x-holdPoint.x,u.y-holdPoint.y)<9);expect(parkedGarrison.length,`Living garrison left near the Mossgate hall: ${parkedGarrison.length}`).toBeGreaterThan(0);
 await page.locator('#save').click();await page.reload();await page.locator('#start').click();if((await read(page)).speed)await page.locator('#pause').click();await page.locator('#tab-empire').click();await expect(page.locator('#travel-region')).toBeEnabled({timeout:30000});await page.locator('#travel-region').click();state=await read(page);expect(state.region).toBe('march');expect(state.march.rival.status).toBe('captured');expect(state.buildings.some((b:any)=>b.id===addedCottage.id&&b.x===previewSite.x&&b.y===previewSite.y&&b.owner!=='rival')).toBe(true);const returnedGarrison=state.units.filter((u:any)=>stationedIds.includes(u.id)&&!travelIds.includes(u.id)&&u.hp>0&&Math.hypot(u.x-holdPoint.x,u.y-holdPoint.y)<9);expect(returnedGarrison.length).toBeGreaterThan(0);await page.locator('#save').click();await page.reload();await page.locator('#start').click();state=await read(page);expect(state.march.rival.status).toBe('captured');expect(state.buildings.some((b:any)=>b.id===addedCottage.id&&b.owner!=='rival')).toBe(true);expect(errors).toEqual([]);
 const accounting=await page.evaluate((ids:number[])=>{const rt=(window as any).__KINGNAMIC__.runtime,s=rt.state,worlds=[s,...(s.empire?[s.empire.reserve]:[])],records=new Map<number,any>();for(const w of worlds)for(const u of w.units)if(u.hp>0&&['warden','ranger','spearman','scout'].includes(u.kind))records.set(u.id,{id:u.id,kind:u.kind,region:w.region??'hearthmere',hp:u.hp,maxHp:u.maxHp,injury:u.injury??0,order:u.order??'none',target:u.target,squadId:u.squadId??null});const alive=new Set(records.keys()),fallen=new Set(worlds.flatMap((w:any)=>w.fallenIds??[])),corpses=new Set(worlds.flatMap((w:any)=>(w.corpses??[]).map((c:any)=>c.personId))),risen=new Set(worlds.flatMap((w:any)=>w.units.filter((u:any)=>u.reanimatedFrom!==undefined).map((u:any)=>u.reanimatedFrom)));const rows=ids.map(id=>{const record=records.get(id);return{...(record??{id,kind:'unknown',region:null}),alive:alive.has(id),fallen:fallen.has(id),corpse:corpses.has(id),reanimated:risen.has(id)};});return{total:ids.length,accounted:rows.filter(x=>x.alive||x.fallen).length,alive:rows.filter(x=>x.alive).length,fallen:rows.filter(x=>x.fallen).length,pendingCorpse:rows.filter(x=>x.fallen&&x.corpse&&!x.reanimated).length,reanimated:rows.filter(x=>x.reanimated).length,settledDead:rows.filter(x=>x.fallen&&!x.corpse&&!x.reanimated).length,unaccounted:rows.filter(x=>!x.alive&&!x.fallen),duplicated:rows.filter(x=>x.alive&&x.fallen),roster:rows};},companyIds);
 expect(accounting.accounted).toBe(forceSize);expect(accounting.unaccounted).toEqual([]);expect(accounting.duplicated).toEqual([]);
 await writeFile('docs/evidence/mossgate-natural-siege.json',JSON.stringify({fixtureSetup:'Mature starting save: 110 new fit residents and a level-three garrison network; all reinforcements were recruited through command() with original game eligibility/cost/ID logic. Travel, company deployment, protected formation, role-specific orders, gate breach, combat simulation, casualty accounting, capture, player construction, garrison defense orders, live clearing of post-capture threats, region departure, revisit and offline reload were live. No battle state or capture counters were edited.',forceComposition:recruitment,startingSoldiers:forceSize,liveCombat:history,performance:perf,cleanupHunt,occupation:{addedBuilding:{kind:'cottage',id:addedCottage.id,site:{x:addedCottage.x,y:addedCottage.y}},stationedSoldiers:stationedIds.length,livingGarrisonAfterThreatClear:garrisonSurvivorIds.length,threatsBeforeConvoy:nearbyThreats.length,threatsClearedForTravel,before:beforeOrganization,organization,leftAndReturned:true,persistedAfterReload:true},accounting,final:{status:state.march.rival.status,casualties:state.march.rival.casualties,remaining:state.march.rival.remaining,reserve:state.march.rival.reserve,companySurvivors:state.units.filter((u:any)=>companyIds.includes(u.id)&&u.hp>0).length,playerLost:state.stats.lost,infected:foes(state).length,saveReloaded:true,errors}},null,2));
});
