import {test,expect} from '@playwright/test';
import {writeFile} from 'node:fs/promises';

test('attribute remaining 200-soldier stalls across UI, scene, simulation, saves and WebGL render',async({page})=>{
 await page.goto('/');await page.bringToFront();await page.locator('#start').click();await page.evaluate(async()=>{
  const load=(p:string)=>import(/* @vite-ignore */p),{newGame,army,makeUnit}=await load('/src/game/state.ts'),{command}=await load('/src/game/commands.ts'),{nearestOpen}=await load('/src/game/navigation.ts'),{key}=await load('/src/game/map.ts');
  const s=newGame();s.resources={wood:4000,stone:3000,food:4000,herbs:100};command(s,{type:'commander-appoint'});for(const u of army(s))Object.assign(u,{x:14,y:24});command(s,{type:'travel',ids:army(s).map((u:any)=>u.id)});s.units=army(s);command(s,{type:'build',kind:'hearth',x:16,y:21});s.units=[];const reserved=new Set<number>(s.residents.map(key));
  for(let n=0;n<200;n++){const p=nearestOpen(s,{x:11+n%11,y:11+Math.floor(n/11)},reserved);reserved.add(key(p));makeUnit(s,['warden','ranger','spearman','scout'][n%4],p.x,p.y);}command(s,{type:'commander-appoint',id:s.units[0].id});command(s,{type:'order',order:'hunt',ids:army(s).map((u:any)=>u.id),x:21,y:12});
  for(let n=0;n<120;n++){const p=nearestOpen(s,{x:26,y:8+n%8},reserved);reserved.add(key(p));makeUnit(s,n%7===0?'brute':n%3===0?'runner':'hollow',p.x,p.y);}command(s,{type:'speed',speed:0});const rt=(window as any).__KINGNAMIC__.runtime;rt.state=s;rt.onChange();
 });await page.locator('#tab-army').click();await page.locator('#speed-2').click();
 const profiler=await page.context().newCDPSession(page);await profiler.send('Profiler.enable');await profiler.send('Profiler.setSamplingInterval',{interval:1000});await profiler.send('Profiler.start');const profileAnchor=await page.evaluate(()=>performance.now());
 const result=await page.evaluate(async()=>{
  const {Interface}=await import('/src/ui/interface.ts' as string),a=(window as any).__KINGNAMIC__,timings:Record<string,number[]>={},events:Record<string,{atMs:number;durationMs:number}[]>={},restore:(()=>void)[]=[],longTasks:any[]=[],frameSpikes:any[]=[],captureStart=performance.now();
  const wrap=(obj:any,key:string,name:string)=>{const fn=obj[key],out:number[]=[],samples:{atMs:number;durationMs:number}[]=[];timings[name]=out;events[name]=samples;obj[key]=function(...args:any[]){const t=performance.now();try{return fn.apply(this,args);}finally{const durationMs=performance.now()-t;out.push(durationMs);if(durationMs>=8)samples.push({atMs:t-captureStart,durationMs});}};restore.push(()=>obj[key]=fn);};
  wrap(Interface.prototype,'render','ui');wrap(a.runtime,'tick','simulation');wrap(a.runtime,'persist','save');wrap(a.scene.sys,'sceneUpdate','sceneInclusive');wrap(a.game.renderer,'render','webglRender');
  const observer=new PerformanceObserver(list=>{for(const e of list.getEntries())longTasks.push({startMs:e.startTime-captureStart,durationMs:e.duration});});observer.observe({entryTypes:['longtask']});const start=performance.now(),sim=a.runtime.state.time,frames:number[]=[];let previous=start;
  try{await new Promise<void>(resolve=>{const f=(now:number)=>{const durationMs=now-previous;frames.push(durationMs);if(durationMs>=20)frameSpikes.push({atMs:now-captureStart,durationMs});previous=now;if(now-start<45000)requestAnimationFrame(f);else resolve();};requestAnimationFrame(f);});}finally{for(const f of restore)f();observer.disconnect();}
  timings.frames=frames.slice(1);const results=Object.fromEntries(Object.entries(timings).map(([k,v])=>{v.sort((a,b)=>a-b);return [k,{samples:v.length,p95Ms:v[Math.floor(v.length*.95)]??0,maxMs:v.at(-1)??0}];}));const wrapperSpikes=Object.fromEntries(Object.entries(events).map(([name,samples])=>[name,samples.filter(sample=>sample.durationMs>=8)]));return {captureStartAtMs:captureStart,wallMs:performance.now()-start,simulationSeconds:a.runtime.state.time-sim,results,longTasks,spikes:{frame:frameSpikes,wrappersAtLeast8Ms:wrapperSpikes},browser:{visibility:document.visibilityState,focused:document.hasFocus(),devicePixelRatio},renderer:a.game.renderer.type,rendererDetails:(()=>{const gl:any=a.game.canvas.getContext('webgl2')??a.game.canvas.getContext('webgl'),debug=gl?.getExtension('WEBGL_debug_renderer_info');return {vendor:gl?.getParameter(debug?debug.UNMASKED_VENDOR_WEBGL:gl.VENDOR),renderer:gl?.getParameter(debug?debug.UNMASKED_RENDERER_WEBGL:gl.RENDERER)};})()};
 });const {profile}=await profiler.send('Profiler.stop');await profiler.detach();
 const byId=new Map(profile.nodes.map((node:any)=>[node.id,node])),parents=new Map<number,number>(),self=new Map<string,number>(),inclusive=new Map<string,number>();
 for(const node of profile.nodes)for(const child of node.children??[])parents.set(child,node.id);
 const frameKey=(node:any)=>`${node.callFrame.url.split('?')[0]}:${node.callFrame.functionName||'(anonymous)'}:${node.callFrame.lineNumber+1}`;
 let profileUs=0;for(let i=0;i<profile.samples.length;i++){const id=profile.samples[i],delta=profile.timeDeltas[i]??1000;profileUs+=delta;let node=byId.get(id);if(node)self.set(frameKey(node), (self.get(frameKey(node))??0)+delta);while(node){const key=frameKey(node);inclusive.set(key,(inclusive.get(key)??0)+delta);node=byId.get(parents.get(node.id)??-1);}}
 const rank=(source:Map<string,number>)=>[...source].sort((a,b)=>b[1]-a[1]).slice(0,25).map(([frame,microseconds])=>({frame,milliseconds:Number((microseconds/1000).toFixed(1))}));
 const profileWindows=result.longTasks.map((task:any)=>{const start=task.startMs,end=start+task.durationMs,hot=new Map<string,number>();let elapsedUs=0,maxGapMs=0;for(let i=0;i<profile.samples.length;i++){const delta=profile.timeDeltas[i]??1000,atMs=profileAnchor-result.captureStartAtMs+(elapsedUs+delta)/1000;elapsedUs+=delta;if(delta/1000>maxGapMs&&atMs>=start&&atMs<=end)maxGapMs=delta/1000;if(atMs<start||atMs>end)continue;const node=byId.get(profile.samples[i]);if(node){const frame=frameKey(node);hot.set(frame,(hot.get(frame)??0)+delta);}}return {startMs:start,durationMs:task.durationMs,profileSampledMs:Number(([...hot.values()].reduce((sum,value)=>sum+value,0)/1000).toFixed(1)),largestSampleGapMs:Number(maxGapMs.toFixed(1)),topSelf:[...hot].sort((x,y)=>y[1]-x[1]).slice(0,8).map(([frame,microseconds])=>({frame,milliseconds:Number((microseconds/1000).toFixed(1))}))};});
 await page.locator('#pause').click();
 // Sampling volume is a measurement-validity floor, not a frame-rate goal.
 // Constrained/headless GPU environments can produce far fewer than 1,000
 // WebGL frames in 45 seconds; the report retains the actual count and timing.
 expect(result.results.ui.samples).toBeGreaterThan(80);expect(result.results.webglRender.samples).toBeGreaterThan(80);await writeFile('docs/evidence/empire-hitch-attribution.json',JSON.stringify({fixture:true,method:'45-second prepared 200-soldier / 120-infected battle at 2x; wrapper durations include nested work and are not additive. Chrome V8 CPU sampling interval 1 ms; sampled inclusive and self-time rankings are attribution clues, not exclusive wall-clock measurements. Long tasks, RAF gaps and subsystem wrappers share performance.now() time, and CPU profile sample windows are aligned approximately from the profile-start acknowledgment.',...result,cpuProfile:{samples:profile.samples.length,sampledMilliseconds:Number((profileUs/1000).toFixed(1)),topInclusive:rank(inclusive),topSelf:rank(self),longTaskWindows:profileWindows},},null,2));
});
