import {test,expect} from '@playwright/test';
import {writeFile} from 'node:fs/promises';

const read=(page:any)=>page.evaluate(()=>JSON.parse(JSON.stringify((window as any).__KINGNAMIC__.runtime.state)));
const click=(page:any,selector:string)=>page.locator(selector).evaluate((el:any)=>(el as HTMLElement).click());

test('Mossgate discovery, a live siege strike, and fixture-assisted capture persist in browser',async({page})=>{
 test.setTimeout(240000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await click(page,'#start');await page.waitForFunction(()=>!!(window as any).__KINGNAMIC__);if((await read(page)).speed)await click(page,'#pause');
 const setup=await page.evaluate(async()=>{
  const setupUnitSummary=(s:any)=>s.units.map((u:any)=>({kind:u.kind,id:u.id,faction:u.faction,x:u.x,y:u.y})).slice(0,8);
  const g:any=window as any,rt=g.__KINGNAMIC__.runtime;
  const {army,makeUnit}=await import('/src/game/state.ts' as string);
  const {empireStep}=await import('/src/game/empire.ts' as string);
  if(!rt.state.commander)rt.act({type:'commander-appoint'});
  const origin=army(rt.state);
  for(const u of origin)Object.assign(u,{x:14,y:24,target:{x:14,y:24},order:'hold'});
  const departed=rt.act({type:'travel',ids:origin.map((u:any)=>u.id)});if(!departed.ok)throw Error(departed.message);
  const s=rt.world,hero=s.units.find((u:any)=>u.id===s.commander.id);
  for(let n=0;n<24;n++)makeUnit(s,'warden',40+n%5,26+Math.floor(n/5));
  const friends=army(s);for(let i=0;i<friends.length;i++)Object.assign(friends[i],{x:40+i%5,y:26+Math.floor(i/5),target:{x:40+i%5,y:26+Math.floor(i/5)},order:'hold'});
  Object.assign(hero,{x:42,y:29,target:{x:42,y:29},order:'hold'});empireStep(s,.1);
  const scene=g.__KINGNAMIC__.scene;
  const gate=s.buildings.find((b:any)=>b.owner==='rival'&&b.kind==='gate');if(!gate)throw Error('Mossgate gate missing: '+JSON.stringify({region:s.region,hero,war:s.march?.rival,rivalBuildings:s.buildings.filter((b:any)=>b.owner==='rival').map((b:any)=>({kind:b.kind,x:b.x,y:b.y})),rivals:s.units.filter((u:any)=>u.faction==='rival').length,worldUnits:s.units.length,inf:setupUnitSummary(s)}));
  rt.onChange();rt.persist();return {hero:hero.id,gate:gate.id,position:{x:gate.x,y:gate.y},garrison:s.march.rival.remaining,reserve:s.march.rival.reserve,infected:s.units.filter((u:any)=>['hollow','runner','brute'].includes(u.kind)).length,activeUnits:s.units.length,sceneryProps:(scene as any).scenery.length};
 });
 await page.evaluate((p:any)=>(window as any).__KINGNAMIC__.scene.focus(p),{x:47,y:29});await page.waitForTimeout(450);
 let state=await read(page);expect(state.region).toBe('march');expect(state.march.rival.status).toBe('occupied');expect(setup.garrison).toBe(100);expect(setup.reserve).toBe(80);expect(setup.infected).toBeGreaterThan(0);
 await click(page,'#tab-empire');await page.screenshot({path:'docs/evidence/mossgate-first-sight.png'});
 await click(page,'#tab-army');await page.locator('#army-orders').click();await page.locator('#select-all').click();await page.locator('#order-attack').click();
 const canvas=page.locator('#world canvas'),box=await canvas.boundingBox(),target=await page.evaluate((p:any)=>(window as any).__KINGNAMIC__.scene.screenPoint(p),setup.position);expect(box).not.toBeNull();
 await page.mouse.click(box!.x+target.x,box!.y+target.y-10,{button:'right'});await page.screenshot({path:'docs/evidence/mossgate-command-preview.png'});
 await expect.poll(async()=>{const s=await read(page);return s.units.filter((u:any)=>!u.faction&&['warden','ranger','spearman','scout'].includes(u.kind)&&u.order==='attack'&&u.focus===setup.gate).length;},{timeout:5000}).toBeGreaterThan(0);
 state=await read(page);const gateBefore=state.buildings.find((b:any)=>b.id===setup.gate).hp;await click(page,'#speed-1');const perf=await page.evaluate(async()=>{const rt=(window as any).__KINGNAMIC__.runtime,scene=(window as any).__KINGNAMIC__.scene,before=rt.world.time,start=performance.now();let frames=0,elapsed=0,tickMs=0;const tick=rt.tick;rt.tick=function(delta:number){const t=performance.now(),value=tick.call(this,delta);tickMs+=performance.now()-t;return value;};await new Promise<void>(resolve=>{const frame=()=>{frames++;elapsed=performance.now()-start;if(elapsed<1000)requestAnimationFrame(frame);else resolve();};requestAnimationFrame(frame);});const props=(scene as any).scenery as any[];return {wallMs:Math.round(elapsed),frames,framesPerSecond:Math.round(frames*1000/elapsed),simulationSeconds:Number((rt.world.time-before).toFixed(2)),activeUnits:rt.world.units.length,rivalUnits:rt.world.units.filter((u:any)=>u.faction==='rival').length,runtimeTickMs:Number(tickMs.toFixed(1)),sceneryProps:props.length,visibleScenery:props.filter(p=>p.sprite?.visible).length};});
 expect(perf.runtimeTickMs).toBeLessThan(500);
 await expect.poll(async()=>{const s=await read(page);return s.march.rival.casualties>0||s.buildings.find((b:any)=>b.id===setup.gate)?.hp<gateBefore;},{timeout:20000}).toBe(true);
 await click(page,'#pause');const live=await read(page);await page.screenshot({path:'docs/evidence/mossgate-siege.png'});
 await page.evaluate(()=>{const rt=(window as any).__KINGNAMIC__.runtime,s=rt.world,w=s.march.rival,dead=s.units.filter((u:any)=>u.faction==='rival').map((u:any)=>u.id);s.units=s.units.filter((u:any)=>u.faction!=='rival'&&!['hollow','runner','brute'].includes(u.kind));s.infection=s.infection.filter((i:any)=>!dead.includes(i.personId));s.corpses=(s.corpses??[]).filter((c:any)=>!c.tainted||Math.hypot(c.x-47,c.y-29)>=7);w.remaining=0;w.reserve=0;w.casualties=100;w.leaderId=undefined;const hero=s.units.find((u:any)=>u.id===s.commander.id);Object.assign(hero,{x:47,y:29});rt.onChange();});
 await click(page,'#tab-empire');await expect(page.locator('#capture-stronghold')).toBeEnabled();await click(page,'#capture-stronghold');
 state=await read(page);expect(state.march.rival.status).toBe('captured');expect(state.march.secured).toBe(true);expect(state.buildings.find((b:any)=>b.name==='Mossgate Hall').owner).toBe('player');expect(state.population).toBe(4);
 const existingCottages=state.buildings.filter((b:any)=>b.kind==='cottage').map((b:any)=>b.id),buildSite=await page.evaluate(async()=>{const {buildError}=await import('/src/game/commands.ts' as string),s=(window as any).__KINGNAMIC__.runtime.world,sites:any[]=[];for(let radius=1;radius<=10&&!sites.length;radius++)for(let y=29-radius;y<=29+radius;y++)for(let x=47-radius;x<=47+radius;x++)if(Math.max(Math.abs(x-47),Math.abs(y-29))===radius&&!buildError(s,'cottage',x,y))sites.push({x,y});return sites[0]??null;});
 expect(buildSite).not.toBeNull();await click(page,'#tab-build');await click(page,'#category-settlement');await click(page,'#build-cottage');await page.evaluate((p:any)=>(window as any).__KINGNAMIC__.scene.focus(p),buildSite);await page.waitForTimeout(450);
 const buildCanvas=page.locator('#world canvas'),buildBox=await buildCanvas.boundingBox(),buildPoint=await page.evaluate((p:any)=>(window as any).__KINGNAMIC__.scene.screenPoint(p),buildSite);if(!buildBox)throw Error('world canvas is not visible');await page.mouse.move(buildBox.x+buildPoint.x,buildBox.y+buildPoint.y);await page.waitForTimeout(80);await page.screenshot({path:'docs/evidence/mossgate-placement-preview.png'});await page.mouse.click(buildBox.x+buildPoint.x,buildBox.y+buildPoint.y);state=await read(page);const placed=state.buildings.find((b:any)=>b.kind==='cottage'&&!existingCottages.includes(b.id));expect(placed).toMatchObject({x:buildSite.x,y:buildSite.y});expect(placed.owner).not.toBe('rival');
 await page.screenshot({path:'docs/evidence/mossgate-captured.png'});await click(page,'#save');expect(await page.locator('#save-status').textContent()).not.toContain('unavailable');await page.reload();await click(page,'#start');await page.waitForTimeout(100);if((await read(page)).speed)await click(page,'#pause');state=await read(page);expect(state.march.rival.status).toBe('captured');expect(state.buildings.find((b:any)=>b.name==='Mossgate Hall').owner).toBe('player');expect(state.buildings.some((b:any)=>b.id===placed.id&&b.kind==='cottage'&&b.x===buildSite.x&&b.y===buildSite.y&&b.owner!=='rival')).toBe(true);expect(errors).toEqual([]);
 await writeFile('docs/evidence/mossgate-browser.json',JSON.stringify({fixture:true,fixtureDetails:'Discovery and the opening siege are simulated in browser with a 27-soldier company; attack orders are issued through the UI, and the test requires live Gloamward casualties or gate damage. A fixture then clears remaining defenders to verify the gated capture reward, player-placed cottage, save and reload. This is not an unaided full siege or a human playtest.',liveBeforeFixture:{casualties:live.march.rival.casualties,defendersRemaining:live.march.rival.remaining,reliefRemaining:live.march.rival.reserve,gateHp:live.buildings.find((b:any)=>b.id===setup.gate)?.hp,playerSoldiers:live.units.filter((u:any)=>!u.faction&&['warden','ranger','spearman','scout'].includes(u.kind)).length,lost:live.stats.lost,slain:live.stats.slain},settlementConstruction:{kind:'cottage',site:buildSite,persisted:true},performance:{...perf,sceneryProps:setup.sceneryProps},region:state.region,war:state.march.rival,settlements:state.buildings.filter((b:any)=>b.kind==='hearth').map((b:any)=>({name:b.name,owner:b.owner,hp:b.hp,maxHp:b.maxHp})),army:state.units.filter((u:any)=>['warden','ranger','spearman','scout'].includes(u.kind)).length,infectedAtDiscovery:setup.infected,errors},null,2));
});
