import {test,expect,type Page} from '@playwright/test';
import {writeFile} from 'node:fs/promises';
import {newGame,army,makeBuilding} from '../../src/game/state';
import {commandableIds} from '../../src/game/army';
import {addResidents} from '../../src/game/population';
import {command} from '../../src/game/commands';
import {decode} from '../../src/game/persistence';
import type {SoldierKind} from '../../src/game/types';
if(process.env.KINGNAMIC_HARDWARE_PROFILE==='1')test.use({launchOptions:{args:['--enable-gpu','--use-gl=angle','--use-angle=d3d11']}});

const read=(page:Page)=>page.evaluate(()=>JSON.parse(JSON.stringify((window as any).__KINGNAMIC__.runtime.state)));
const clickLive=(page:Page,selector:string)=>page.evaluate((sel:string)=>new Promise<void>((resolve,reject)=>{let frames=0;const attempt=()=>{const button=document.querySelector<HTMLButtonElement>(sel);if(button&&!button.disabled){button.click();resolve();return;}if(++frames>600){reject(new Error(`${sel} stayed unavailable for 10 seconds`));return;}requestAnimationFrame(attempt);};attempt();}),selector);
const waitRegion=(page:Page,region:'march'|'heartmere')=>expect.poll(async()=>{const s=await read(page);return s.region??'heartmere';},{timeout:45000,intervals:[100,250,500]}).toBe(region);
const forceSize=180;
test('a prepared 180-soldier company naturally defeats and settles Tallowmere, then saves and revisits it',async({page})=>{
 test.setTimeout(900000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 const s=newGame(604271);s.speed=0;s.resources={wood:2200,stone:5200,food:10000,herbs:160};
 const barracks=s.buildings.find(b=>b.kind==='barracks')!;barracks.level=3;makeBuilding(s,'barracks',19,10,true).level=3;makeBuilding(s,'barracks',21,10,true).level=3;addResidents(s,210);
 const startingIds=new Set(army(s).map(u=>u.id)),recruitment:[SoldierKind,number][]=[['warden',55],['spearman',60],['ranger',41],['scout',24]],results:string[]=[];
 for(const [kind,count]of recruitment){const r=command(s,{type:'recruit',kind,count});if(!r.ok)throw Error(`Normal recruitment of ${count} ${kind} failed: ${r.message}`);results.push(r.message);}
 const force=army(s),commander=force.find(u=>u.kind==='warden')!,company=force.filter(u=>!startingIds.has(u.id));expect(company).toHaveLength(forceSize);expect(command(s,{type:'commander-appoint',id:commander.id}).ok).toBe(true);
 const companyIds=company.map(u=>u.id),expeditionIds=[commander.id,...companyIds],take=(kind:SoldierKind,count:number)=>company.filter(u=>u.kind===kind).slice(0,count).map(u=>u.id),vanguard=[commander.id,...take('warden',34),...take('spearman',35),...take('ranger',20),...take('scout',10)],reserves=companyIds.filter(id=>!vanguard.includes(id)),prepared=decode(JSON.stringify(s));expect(vanguard).toHaveLength(100);expect(reserves).toHaveLength(81);expect(prepared,'The prepared force must pass normal save validation.').toBeTruthy();
 await page.goto('/');await page.bringToFront();await page.evaluate(raw=>localStorage.setItem('kingnamic.save.v2',raw),JSON.stringify(s));await page.reload();await page.locator('#start').click();expect((await read(page)).units.filter((u:any)=>companyIds.includes(u.id))).toHaveLength(forceSize);
 await page.locator('#tab-army').click();await page.evaluate((ids:number[])=>(window as any).__KINGNAMIC__.runtime.selectUnits(ids),vanguard);await page.locator('#tab-empire').click();await page.locator('#gather-road').click();await page.locator('#speed-2').click();await expect(page.locator('#travel-region')).toBeEnabled({timeout:120000});await clickLive(page,'#travel-region');await waitRegion(page,'march');
 let state=await read(page);expect(state.units.filter((u:any)=>vanguard.includes(u.id))).toHaveLength(vanguard.length);const heroId=state.commander.id;
 const road=[{x:14,y:32},{x:21,y:38},{x:29,y:39},{x:28,y:44}];
 await page.evaluate((ids:number[])=>(window as any).__KINGNAMIC__.runtime.act({type:'formation',formation:'protected',ids}),vanguard);await page.locator('#speed-2').click();
 const vanguardBody=vanguard.filter(id=>id!==heroId);
 const moveGroup=async(ids:number[],p:{x:number;y:number})=>{const r=await page.evaluate(({ids,p}:{ids:number[];p:{x:number;y:number}})=>{const rt=(window as any).__KINGNAMIC__.runtime;return rt.act({type:'order',order:'move',ids,x:p.x,y:p.y});},{ids,p});if(!r.ok){const v=await read(page);throw new Error(`Move group to ${p.x},${p.y} failed: ${r.message}; ${JSON.stringify({speed:v.speed,commander:v.units.find((u:any)=>u.id===heroId),war:v.march.weirward,player:v.units.filter((u:any)=>ids.includes(u.id)).map((u:any)=>({id:u.id,hp:u.hp,injury:u.injury,infection:v.infection?.find((i:any)=>i.personId===u.id)?.stage,x:u.x,y:u.y})).slice(0,12),missing:ids.filter(id=>!v.units.some((u:any)=>u.id===id)).length})}`);}};
 await moveGroup(vanguardBody,road[0]);
 for(let i=0;i<road.length;i++){
  const waypoint=road[i];
  await expect.poll(async()=>{const v=await read(page);return v.units.filter((u:any)=>vanguardBody.includes(u.id)&&Math.hypot(u.x-waypoint.x,u.y-waypoint.y)<4).length;},{timeout:90000,intervals:[500,1000,2000]}).toBeGreaterThan(8);
  const leader=await page.evaluate(({id,p}:{id:number;p:{x:number;y:number}})=>{const rt=(window as any).__KINGNAMIC__.runtime;return rt.act({type:'order',order:'move',ids:[id],x:p.x,y:p.y});},{id:heroId,p:waypoint});expect(leader.ok).toBe(true);
  await moveGroup(vanguardBody,i<road.length-1?road[i+1]:{x:30,y:44});
  await expect.poll(async()=>{const v=await read(page),hero=v.units.find((u:any)=>u.id===heroId);return hero&&Math.hypot(hero.x-waypoint.x,hero.y-waypoint.y)<1.2;},{timeout:45000,intervals:[500,1000,2000]}).toBe(true);
  const progress=await read(page),walking=progress.units.find((u:any)=>u.id===heroId);console.log('Frontier road checkpoint',JSON.stringify({waypoint,commander:{x:walking?.x,y:walking?.y,target:walking?.target,order:walking?.order},distanceToHall:walking&&Math.hypot(walking.x-37,walking.y-36),status:progress.march.weirward.status,activeRivals:progress.units.filter((u:any)=>u.rivalId==='tallowmere').length,playerAlive:progress.units.filter((u:any)=>vanguard.includes(u.id)).length,lost:progress.stats.lost}));
 }
 await expect.poll(async()=>((await read(page)).march.seen.includes('wayfarer-camp')),{timeout:10000,intervals:[250,500]}).toBe(true);
 await expect.poll(async()=>{const v=await read(page),hero=v.units.find((u:any)=>u.id===heroId);return v.march.seen.includes('wayfarer-camp')&&hero&&Math.hypot(hero.x-28,hero.y-44)<1.2&&v.units.filter((u:any)=>companyIds.includes(u.id)&&Math.hypot(u.x-28,u.y-44)<4).length>10;},{timeout:180000,intervals:[500,1000,2000]}).toBe(true);
 state=await read(page);expect(state.march.rumors).toContain('weirward');const scoutingCommander=state.units.find((u:any)=>u.id===heroId);expect(state.march.weirward.status,`The camp scout should remain outside the keep's radius: ${JSON.stringify({commander:{x:scoutingCommander?.x,y:scoutingCommander?.y,target:scoutingCommander?.target,order:scoutingCommander?.order,path:scoutingCommander?.path},distanceToHall:scoutingCommander&&Math.hypot(scoutingCommander.x-37,scoutingCommander.y-36),units:state.units.length,defenders:state.march.weirward,activeRivals:state.units.filter((u:any)=>u.rivalId==='tallowmere').length})}`).toBe('unseen');await page.evaluate(()=>{const rt=(window as any).__KINGNAMIC__.runtime;rt.heroMode=false;rt.heroWalk={x:0,y:0};rt.onChange();(window as any).__KINGNAMIC__.scene.focus({x:28,y:44});});
 await page.locator('#tab-empire').click();await page.screenshot({path:'docs/evidence/tallowmere-scout-report.png'});
 // Keep the first 99 troops on the road camp while the commander returns home to
 // collect the second convoy. This exercises the real travel limit without
 // changing army transport or silently leaving recruited troops behind.
 await page.evaluate((id:number)=>(window as any).__KINGNAMIC__.runtime.selectUnits([id]),heroId);
 for(const p of [{x:29,y:39},{x:21,y:38},{x:14,y:32},{x:14,y:24}]){
  const r=await page.evaluate(({id,p}:{id:number;p:{x:number;y:number}})=>(window as any).__KINGNAMIC__.runtime.act({type:'order',order:'move',ids:[id],x:p.x,y:p.y}),{id:heroId,p});expect(r.ok).toBe(true);
  await expect.poll(async()=>{const v=await read(page),hero=v.units.find((u:any)=>u.id===heroId);return hero&&Math.hypot(hero.x-p.x,hero.y-p.y)<1.2;},{timeout:60000,intervals:[500,1000,2000]}).toBe(true);
 }
 await page.locator('#tab-empire').click();await expect(page.locator('#travel-region')).toBeEnabled({timeout:30000});await clickLive(page,'#travel-region');await waitRegion(page,'heartmere');
 state=await read(page);expect(state.units.filter((u:any)=>u.id===heroId)).toHaveLength(1);expect(state.units.filter((u:any)=>reserves.includes(u.id))).toHaveLength(reserves.length);expect(state.empire.reserve.units.filter((u:any)=>vanguardBody.includes(u.id))).toHaveLength(vanguardBody.length);
 await page.locator('#speed-2').click();await page.locator('#tab-army').click();await page.evaluate((ids:number[])=>(window as any).__KINGNAMIC__.runtime.selectUnits(ids),reserves);await page.locator('#tab-empire').click();await page.locator('#gather-road').click();await expect(page.locator('#travel-region')).toBeEnabled({timeout:120000});await clickLive(page,'#travel-region');await waitRegion(page,'march');
 state=await read(page);expect(state.units.filter((u:any)=>vanguard.includes(u.id))).toHaveLength(vanguard.length);expect(state.units.filter((u:any)=>reserves.includes(u.id))).toHaveLength(reserves.length);
 await page.evaluate((ids:number[])=>(window as any).__KINGNAMIC__.runtime.act({type:'formation',formation:'protected',ids}),reserves);await page.locator('#speed-2').click();
 await moveGroup(reserves,road[0]);
 for(let i=0;i<road.length;i++){
  const waypoint=road[i];
  // Protected formation deliberately spreads soldiers across a broad front.
  // Count troops settled in their own assigned slots instead of a narrow disk
  // around the formation center.
  await expect.poll(async()=>{const v=await read(page);return v.units.filter((u:any)=>reserves.includes(u.id)&&Math.hypot(u.x-u.target.x,u.y-u.target.y)<1.2).length;},{timeout:90000,intervals:[500,1000,2000]}).toBeGreaterThan(60);
  const leader=await page.evaluate(({id,p}:{id:number;p:{x:number;y:number}})=>(window as any).__KINGNAMIC__.runtime.act({type:'order',order:'move',ids:[id],x:p.x,y:p.y}),{id:heroId,p:waypoint});expect(leader.ok).toBe(true);
  await moveGroup(reserves,i<road.length-1?road[i+1]:{x:30,y:44});
  await expect.poll(async()=>{const v=await read(page),hero=v.units.find((u:any)=>u.id===heroId);return hero&&Math.hypot(hero.x-waypoint.x,hero.y-waypoint.y)<1.2;},{timeout:45000,intervals:[500,1000,2000]}).toBe(true);
 }
 // The final 180-person protected company spans multiple ranks. Verify the
 // actual formation slots around camp instead of requiring a physically
 // impossible pile of 150 soldiers inside a five-tile circle.
 await expect.poll(async()=>{const v=await read(page);return v.units.filter((u:any)=>companyIds.includes(u.id)&&Math.hypot(u.x-u.target.x,u.y-u.target.y)<1.2&&Math.hypot(u.target.x-30,u.target.y-44)<10).length;},{timeout:120000,intervals:[500,1000,2000]}).toBeGreaterThan(150);
 const camp=await page.evaluate((id:number)=>(window as any).__KINGNAMIC__.runtime.act({type:'order',order:'move',ids:[id],x:32,y:42}),heroId);expect(camp.ok).toBe(true);
 await expect.poll(async()=>((await read(page)).march.weirward.status==='occupied'),{timeout:30000,intervals:[500,1000]}).toBe(true);
 await page.locator('#pause').click();
 state=await read(page);expect(state.march.weirward.remaining+state.march.weirward.casualties).toBe(150);expect(state.march.weirward.reserve).toBe(120);expect(state.units.filter((u:any)=>u.faction==='rival'&&u.rivalId==='tallowmere')).toHaveLength(state.march.weirward.remaining-state.march.weirward.reserve);expect(state.march.seen).toContain('wayfarer-camp');
 const initial={activeUnits:state.units.length,playerSoldiers:state.units.filter((u:any)=>companyIds.includes(u.id)).length,compactGarrison:state.units.filter((u:any)=>u.rivalId==='tallowmere').length,reserve:state.march.weirward.reserve,zombies:state.units.filter((u:any)=>['hollow','runner','brute'].includes(u.kind)).length};
 await page.evaluate(()=>{const p=(window as any).__KINGNAMIC__.scene;p.focus({x:37,y:36});});await page.screenshot({path:'docs/evidence/tallowmere-first-sighting.png'});
 const gates=state.buildings.filter((b:any)=>b.owner==='rival'&&b.rivalId==='tallowmere'&&b.kind==='gate');expect(gates.map((b:any)=>b.name).sort()).toEqual(['Causeway Gate','East Postern']);
 const availableIds=new Set(commandableIds(state,companyIds)),meleeIds=state.units.filter((u:any)=>availableIds.has(u.id)&&u.id!==heroId&&(u.kind==='warden'||u.kind==='spearman')).map((u:any)=>u.id),rangedIds=state.units.filter((u:any)=>availableIds.has(u.id)&&u.id!==heroId&&(u.kind==='ranger'||u.kind==='scout')).map((u:any)=>u.id);
 expect(meleeIds.length).toBeGreaterThan(90);expect(rangedIds.length).toBeGreaterThan(45);
 const orders=await page.evaluate(({melee,ranged,west,east}:{melee:number[];ranged:number[];west:number;east:number})=>{const rt=(window as any).__KINGNAMIC__.runtime;rt.act({type:'formation',formation:'protected',ids:[...melee,...ranged]});return[rt.act({type:'order',order:'attack',ids:melee,focus:west}),rt.act({type:'order',order:'attack',ids:ranged,focus:east})];},{melee:meleeIds,ranged:rangedIds,west:gates.find((b:any)=>b.name==='Causeway Gate')!.id,east:gates.find((b:any)=>b.name==='East Postern')!.id});
 expect(orders.every((r:any)=>r.ok),JSON.stringify(orders)).toBe(true);await page.locator('#tab-empire').click();await page.screenshot({path:'docs/evidence/tallowmere-siege-opening.png'});await page.locator('#speed-2').click();
 const performance=await page.evaluate(async()=>{
  const rt=(window as any).__KINGNAMIC__.runtime,tick=rt.tick,counts=()=>({activeUnits:rt.world.units.length,playerSoldiers:rt.world.units.filter((u:any)=>!u.faction&&['warden','spearman','ranger','scout'].includes(u.kind)).length,compactGarrison:rt.world.units.filter((u:any)=>u.faction==='rival'&&u.rivalId==='tallowmere').length,infected:rt.world.units.filter((u:any)=>['hollow','runner','brute'].includes(u.kind)).length,defendersRemaining:rt.world.march?.weirward?.remaining,reserve:rt.world.march?.weirward?.reserve});
  const atStart=counts(),tickTimes:number[]=[],frameTimes:number[]=[],tickSpikes:{startMs:number;durationMs:number}[]=[],longTasks:{startMs:number;durationMs:number}[]=[],sampleStart=performance.now(),observer=typeof PerformanceObserver==='undefined'?undefined:new PerformanceObserver((list:any)=>longTasks.push(...list.getEntries().map((e:any)=>({startMs:e.startTime-sampleStart,durationMs:e.duration}))));try{observer?.observe({entryTypes:['longtask']});}catch{}
  rt.tick=function(delta:number){const tickStart=performance.now(),value=tick.call(this,delta),duration=performance.now()-tickStart;tickTimes.push(duration);if(duration>50)tickSpikes.push({startMs:Number((tickStart-sampleStart).toFixed(1)),durationMs:Number(duration.toFixed(1))});return value;};
  const start=sampleStart;await new Promise<void>(resolve=>{let last=start;const frame=(now:number)=>{frameTimes.push(now-last);last=now;if(now-start<5000)requestAnimationFrame(frame);else resolve();};requestAnimationFrame(frame);});rt.tick=tick;observer?.disconnect();frameTimes.sort((a,b)=>a-b);tickTimes.sort((a,b)=>a-b);
  const canvas=document.querySelector('canvas'),gl=canvas?.getContext('webgl2')??canvas?.getContext('webgl'),debug=gl?.getExtension('WEBGL_debug_renderer_info') as any;
  const {navigationMetrics}=await import('/src/game/navigation.ts' as string);
  return{wallMs:Math.round(performance.now()-start),fps:Math.round(frameTimes.length*1000/(performance.now()-start)),frameMedianMs:Number((frameTimes[Math.floor(frameTimes.length*.5)]??0).toFixed(2)),frameP95Ms:Number((frameTimes[Math.floor(frameTimes.length*.95)]??0).toFixed(2)),frameWorstMs:Number((frameTimes.at(-1)??0).toFixed(2)),tickMedianMs:Number((tickTimes[Math.floor(tickTimes.length*.5)]??0).toFixed(3)),tickP95Ms:Number((tickTimes[Math.floor(tickTimes.length*.95)]??0).toFixed(3)),tickWorstMs:Number((tickTimes.at(-1)??0).toFixed(3)),tickSpikes,longTasks,longTasksOver50ms:longTasks.filter(t=>t.durationMs>50).length,atStart,atEnd:counts(),navigation:{...navigationMetrics},memory:(performance as any).memory?{usedJSHeapSize:(performance as any).memory.usedJSHeapSize,totalJSHeapSize:(performance as any).memory.totalJSHeapSize}:null,webglRenderer:debug?gl!.getParameter(debug.UNMASKED_RENDERER_WEBGL):gl?.getParameter(gl.RENDERER)??'unavailable',devicePixelRatio,browserFocused:document.hasFocus()};
 });
 const started=Date.now(),history:any[]=[];let logAt=started+15000,cleanupTarget:number|undefined,commanderAdvanced=false;
 while(Date.now()-started<600000){
  await page.waitForTimeout(2500);state=await read(page);const w=state.march.weirward,commander=state.units.find((u:any)=>u.id===heroId),zombies=state.units.filter((u:any)=>['hollow','runner','brute'].includes(u.kind)&&u.hp>0),snap={elapsedMs:Date.now()-started,remaining:w.remaining,reserve:w.reserve,activeCompact:state.units.filter((u:any)=>u.faction==='rival'&&u.rivalId==='tallowmere').length,playerAlive:state.units.filter((u:any)=>companyIds.includes(u.id)).length,playerLost:state.stats.lost,infected:zombies.length,infectedHp:zombies.reduce((sum:number,u:any)=>sum+u.hp,0),commanderHp:commander?.hp,warning:w.warning,gates:state.buildings.filter((b:any)=>b.rivalId==='tallowmere'&&b.kind==='gate').map((b:any)=>({name:b.name,hp:b.hp}))};history.push(snap);
  if(Date.now()>=logAt){console.log('Tallowmere live siege',JSON.stringify(snap));logAt+=20000;}
  if(await page.locator('#capture-tallowmere').count()&&await page.locator('#capture-tallowmere').isEnabled())break;
  if(w.remaining===0&&w.reserve===0&&!state.units.some((u:any)=>u.faction==='rival'&&u.rivalId==='tallowmere')){
   if(!commanderAdvanced){const r=await page.evaluate((id:number)=>(window as any).__KINGNAMIC__.runtime.act({type:'order',order:'move',ids:[id],x:33,y:38}),heroId);expect(r.ok,`The living commander must be able to enter the cleared keep: ${r.message}`).toBe(true);commanderAdvanced=true;}
   const target=[...zombies].sort((a:any,b:any)=>Math.hypot(a.x-37,a.y-36)-Math.hypot(b.x-37,b.y-36))[0];
   if(target&&cleanupTarget!==target.id){const r=await page.evaluate((company:number[])=>{const rt=(window as any).__KINGNAMIC__.runtime,s=rt.state,nearby=s.units.filter((u:any)=>u.hp>0&&['hollow','runner','brute'].includes(u.kind)).sort((a:any,b:any)=>Math.hypot(a.x-37,a.y-36)-Math.hypot(b.x-37,b.y-36)),focus=nearby[0];if(!focus)return{ok:true,cleared:true};const ids=company.filter(id=>{const u=s.units.find((v:any)=>v.id===id);return u&&u.origin!=='battalion'&&u.hp>0&&!u.injury&&!(s.quarantine&&s.infection.some((i:any)=>i.personId===id));});if(!ids.length)return{ok:false,message:`No fit expedition troops remain to attack infected #${focus.id}.`};return{...rt.act({type:'order',order:'attack',ids,focus:focus.id}),focusId:focus.id};},companyIds);expect(r.ok,`The live infected cleanup order must be accepted: ${r.message}`).toBe(true);if(r.ok&&!r.cleared)cleanupTarget=r.focusId;}
  }
 }
 expect(await page.locator('#capture-tallowmere').isEnabled(),`The live assault did not open capture: ${JSON.stringify(history.at(-1))}`).toBe(true);
 await page.locator('#pause').click();state=await read(page);expect(state.march.weirward.remaining+state.march.weirward.casualties).toBe(150);expect(state.march.weirward.casualties).toBe(150);expect(state.march.weirward.reserve).toBe(0);expect(state.units.some((u:any)=>u.faction==='rival'&&u.rivalId==='tallowmere')).toBe(false);expect(errors).toEqual([]);
 await page.screenshot({path:'docs/evidence/tallowmere-garrison-cleared.png'});await page.locator('#capture-tallowmere').click();state=await read(page);expect(state.march.weirward.status).toBe('captured');expect(state.buildings.find((b:any)=>b.name==='Tallowmere Hall')?.owner).toBe('player');expect(state.population).toBe(6);
 const occupiedKeep=state.buildings.find((b:any)=>b.name==='Tallowmere Hall')!,addedSite=await page.evaluate(async()=>{const {buildError}=await import('/src/game/commands.ts' as string),s=(window as any).__KINGNAMIC__.runtime.world,h=s.buildings.find((b:any)=>b.name==='Tallowmere Hall'),choices:any[]=[];for(let radius=1;radius<=9;radius++)for(let y=h.y-radius;y<=h.y+radius;y++)for(let x=h.x-radius;x<=h.x+radius;x++)if(Math.max(Math.abs(x-h.x),Math.abs(y-h.y))===radius&&!buildError(s,'cottage',x,y))choices.push({x,y});return choices[0]??null;});expect(addedSite,'A legitimate cleared building site should be available beside the captured keep.').toBeTruthy();
 const priorBuildingIds=new Set(state.buildings.map((b:any)=>b.id)),built=await page.evaluate((p:{x:number;y:number})=>(window as any).__KINGNAMIC__.runtime.act({type:'build',kind:'cottage',...p}),addedSite);expect(built.ok).toBe(true);state=await read(page);const cottage=state.buildings.find((b:any)=>b.kind==='cottage'&&b.owner!=='rival'&&!priorBuildingIds.has(b.id));expect(cottage).toMatchObject(addedSite);
 const commandable=new Set(commandableIds(state,companyIds)),garrison=state.units.filter((u:any)=>commandable.has(u.id)&&u.id!==heroId&&u.hp>0).slice(0,24).map((u:any)=>u.id);expect(garrison.length).toBeGreaterThan(8);const defense=await page.evaluate(({ids}:{ids:number[]})=>{const rt=(window as any).__KINGNAMIC__.runtime;rt.selectUnits(ids);return rt.act({type:'order',order:'defend',ids,x:38,y:39});},{ids:garrison});expect(defense.ok).toBe(true);
 expect(await page.evaluate(({id,name}:{id:number;name:string})=>(window as any).__KINGNAMIC__.runtime.act({type:'settlement-rename',id,name}),{id:occupiedKeep.id,name:'Saltwick Hall'})).toMatchObject({ok:true});await page.evaluate(()=>{const s=(window as any).__KINGNAMIC__.runtime.world;(window as any).__KINGNAMIC__.scene.focus({x:37,y:36});});await page.screenshot({path:'docs/evidence/tallowmere-settlement.png'});
 const returnCandidates=state.units.filter((u:any)=>commandable.has(u.id)&&u.id!==heroId&&u.hp>0&&!garrison.includes(u.id)).map((u:any)=>u.id);let retreatIds=[heroId,...returnCandidates.slice(0,5)],replacementCommander:number|undefined;
 const fitReturnParty=async()=>{
  let current=await read(page),leader=current.units.find((u:any)=>u.id===current.commander?.id&&u.hp>0&&!u.injury&&!current.infection?.some((i:any)=>i.personId===u.id));
  if(!leader){
   const available=new Set(commandableIds(current,returnCandidates)),next=returnCandidates.find(id=>available.has(id)&&!current.infection?.some((i:any)=>i.personId===id));
   expect(next,'A fit surviving expedition soldier must remain available to lead the return journey.').toBeDefined();
   const appointed=await page.evaluate((id:number)=>(window as any).__KINGNAMIC__.runtime.act({type:'commander-appoint',id}),next!);
   expect(appointed.ok,`Appoint the living expedition survivor after the commander falls: ${appointed.message}`).toBe(true);replacementCommander=next!;current=await read(page);leader=current.units.find((u:any)=>u.id===current.commander?.id&&u.hp>0&&!u.injury&&!current.infection?.some((i:any)=>i.personId===u.id));
  }
  expect(leader,'The return convoy needs a living, fit, uninfected commander.').toBeTruthy();
  const available=new Set(commandableIds(current,returnCandidates)),party=[leader!.id,...returnCandidates.filter(id=>id!==leader!.id&&available.has(id)&&!current.infection?.some((i:any)=>i.personId===id)).slice(0,5)];
  expect(party).toHaveLength(6);retreatIds=party;await page.evaluate((ids:number[])=>(window as any).__KINGNAMIC__.runtime.selectUnits(ids),party);return current;
 };
 await fitReturnParty();await page.locator('#speed-2').click();await page.locator('#tab-empire').click();await clickLive(page,'#gather-road');
 await expect.poll(async()=>{
  const current=await read(page),leader=current.units.find((u:any)=>u.id===current.commander?.id&&u.hp>0&&!u.injury&&!current.infection?.some((i:any)=>i.personId===u.id));
  if(!leader){await fitReturnParty();const gathered=await page.evaluate((ids:number[])=>(window as any).__KINGNAMIC__.runtime.act({type:'gather-company',ids}),retreatIds);expect(gathered.ok,`The replacement commander must be able to gather the surviving return party: ${gathered.message}`).toBe(true);return false;}
  const survivors=retreatIds.every(id=>current.units.some((u:any)=>u.id===id&&u.hp>0&&!u.injury&&!current.infection?.some((i:any)=>i.personId===id)));
  if(!survivors){await fitReturnParty();const gathered=await page.evaluate((ids:number[])=>(window as any).__KINGNAMIC__.runtime.act({type:'gather-company',ids}),retreatIds);expect(gathered.ok,`Refresh the fit return convoy: ${gathered.message}`).toBe(true);return false;}
  return page.evaluate(async()=>{const {travelError}=await import('/src/game/empire.ts' as string),rt=(window as any).__KINGNAMIC__.runtime;return travelError(rt.world,rt.selectedIds)===null;});
 },{timeout:120000,intervals:[500,1000,2000]}).toBe(true);
 await clickLive(page,'#tab-empire');await expect.poll(()=>page.locator('#travel-region').isEnabled(),{timeout:12000}).toBe(true);await clickLive(page,'#travel-region');state=await read(page);expect(state.region).toBeUndefined();expect(state.empire.reserve.march.weirward.status).toBe('captured');expect(state.empire.reserve.buildings.some((b:any)=>b.id===cottage.id)).toBe(true);expect(state.empire.reserve.units.some((u:any)=>garrison.includes(u.id)&&u.order==='defend')).toBe(true);
 await page.locator('#save').click();expect(await page.locator('#save-status').textContent()).toContain('Saved');const savedRaw=await page.evaluate(()=>localStorage.getItem('kingnamic.save.v2'));expect(savedRaw).toBeTruthy();expect(decode(savedRaw!)?.empire?.reserve.march?.weirward?.status).toBe('captured');await page.reload();await page.locator('#start').click();state=await read(page);expect(state.empire.reserve.march.weirward.status).toBe('captured');expect(state.empire.reserve.buildings.find((b:any)=>b.id===cottage.id)).toMatchObject({x:addedSite.x,y:addedSite.y});
 await page.locator('#tab-empire').click();await expect(page.locator('#travel-region')).toBeEnabled({timeout:30000});await clickLive(page,'#travel-region');state=await read(page);expect(state.region).toBe('march');expect(state.march.weirward.status).toBe('captured');expect(state.buildings.some((b:any)=>b.id===cottage.id&&b.owner!=='rival')).toBe(true);expect(state.units.some((u:any)=>garrison.includes(u.id)&&u.order==='defend')).toBe(true);await page.screenshot({path:'docs/evidence/tallowmere-revisited.png'});expect(errors).toEqual([]);
 const accounting=await page.evaluate((ids:number[])=>{const rt=(window as any).__KINGNAMIC__.runtime,s=rt.state,worlds=[s,...(s.empire?[s.empire.reserve]:[])],alive=new Map<number,{count:number;regions:string[]}>(),fallen:number[]=[];for(const w of worlds){const region=w.region??'hearthmere';for(const u of w.units)if(ids.includes(u.id)&&u.hp>0){const r=alive.get(u.id)??{count:0,regions:[]};r.count++;r.regions.push(region);alive.set(u.id,r);}for(const resident of w.residents??[])if(ids.includes(resident.id)&&resident.hp>0){const r=alive.get(resident.id)??{count:0,regions:[]};r.count++;r.regions.push(region);alive.set(resident.id,r);}fallen.push(...(w.fallenIds??[]).filter((id:number)=>ids.includes(id)));}const risen=worlds.flatMap((w:any)=>w.units.filter((u:any)=>u.reanimatedFrom!==undefined).map((u:any)=>u.reanimatedFrom));const rows=ids.map(id=>{const count=alive.get(id)?.count??0,fallenCount=fallen.filter(value=>value===id).length;return{id,alive:count===1,liveCopies:count,fallen:fallenCount===1,fallenCopies:fallenCount,reanimated:risen.includes(id),regions:alive.get(id)?.regions??[]};});return{total:ids.length,alive:rows.filter(r=>r.alive).length,fallen:rows.filter(r=>r.fallen).length,reanimated:rows.filter(r=>r.reanimated).length,unaccounted:rows.filter(r=>!((r.liveCopies===1&&r.fallenCopies===0)||(r.liveCopies===0&&r.fallenCopies===1))),duplicated:rows.filter(r=>r.liveCopies>1||r.fallenCopies>1||r.liveCopies>0&&r.fallenCopies>0),rows};},expeditionIds);expect(accounting.alive+accounting.fallen).toBe(expeditionIds.length);expect(accounting.unaccounted).toEqual([]);expect(accounting.duplicated).toEqual([]);
 const report={forceSize,forceComposition:recruitment,fixtures:'Only resources, home barracks capacity, and fit residents were prepared. Every attacking soldier was recruited with the normal recruitment command and eligibility/cost rules. Travel, patrol discovery, tactical orders, combat, all casualties, cleanup, capture, construction, garrison orders, return, save/reload and revisit were played live. No Tallowmere defender, reserve, casualty, capture flag, or objective was edited by the test.',firstApproach:initial,performance,occupation:{casualties:150,remaining:0,reserve:0,playerLost:state.stats.lost,playerSurvivors:state.units.filter((u:any)=>expeditionIds.includes(u.id)).length,originalCommanderSurvived:state.units.some((u:any)=>u.id===heroId&&u.hp>0),replacementCommander,zombieInteraction:{encountered:history.some((h:any)=>h.infected>0),infectedHpOpening:history.find((h:any)=>h.infected>0)?.infectedHp,infectedHpLatest:history.at(-1)?.infectedHp},settlement:cottage.kind,stationed:garrison.length,renamed:'Saltwick Hall',returnedAndRevisited:true},accounting,siegeSnapshots:history,errors};
 await writeFile('docs/evidence/tallowmere-natural-siege.json',JSON.stringify(report,null,2));
});
