import {describe,it,expect} from 'vitest';
import {newGame,makeUnit,makeBuilding,army} from '../src/game/state';
import {combatStep} from '../src/game/combat';
import {command} from '../src/game/commands';
import {awardBounty} from '../src/game/treasury';
import {decode} from '../src/game/persistence';
import {relocationError} from '../src/game/relocation';
import {navigation,movementBlocker,findPath,clearMelee} from '../src/game/navigation';
import {barrierIndex,barrierMask} from '../src/game/barriers';
import {economyStep,rates} from '../src/game/economy';
import {infect} from '../src/game/disease';
import {key} from '../src/game/map';
import type {SoldierKind} from '../src/game/types';
function arena(){const s=newGame();s.units=[];s.buildings=s.buildings.filter(b=>b.kind==='hearth');s.residents=[];s.population=0;s.jobs={farmers:0,woodcutters:0,miners:0,healers:0,builders:0};s.resources.stone=0;return s;}
function reload<T>(s:T):T {const r=decode(JSON.stringify(s));expect(r).not.toBeNull();return r as T;}
describe('every eligible Crown reward settles once',()=>{
 for(const kind of ['warden','spearman','ranger','scout'] as SoldierKind[])it(kind+' and independent squads receive the same kill reward',()=>{let s=arena();const u=makeUnit(s,kind,10,14);command(s,{type:'squad-create',ids:[u.id],name:'Watch'});u.order='hold';const z=makeUnit(s,'runner',11,14);z.hp=1;s.bountyPaid=40;combatStep(s,.1);expect(s.resources.stone).toBe(2);expect(s.stats.slain).toBe(1);expect(awardBounty(s,z)).toBe(0);s=reload(s);combatStep(s,.1);expect(s.resources.stone).toBe(2);});
 for(const weapon of ['sword','spear','bow'] as const)it('commander '+weapon+' pays once beyond the former cap',()=>{const s=arena(),u=makeUnit(s,'warden',10,14);command(s,{type:'commander-appoint',id:u.id});command(s,{type:'commander-weapon',weapon});const z=makeUnit(s,'brute',11,14);z.hp=1;s.bountyPaid=40;combatStep(s,.1,false,{walk:{x:0,y:0},attack:true,aim:z});expect(s.resources.stone).toBe(3);expect(s.commander!.xp).toBe(1);expect(awardBounty(s,z)).toBe(0);reload(s);});
 it('tower and soldiers resolving simultaneous deaths award the exact enemy sum',()=>{let s=arena();makeBuilding(s,'tower',10,16,true);makeUnit(s,'warden',10,14);makeUnit(s,'ranger',10,14);for(const kind of ['hollow','runner','brute'] as const)makeUnit(s,kind,11,14).hp=1;combatStep(s,.1);expect(s.resources.stone).toBe(6);expect(s.stats.slain).toBe(3);expect(s.logs.some(l=>l.text==='+6 Crowns · 3 infected defeated.')).toBe(true);s=reload(s);combatStep(s,.1);expect(s.resources.stone).toBe(6);});
 it('an infected soldier earns eligible kills but reanimated people cannot be farmed',()=>{const s=arena(),u=makeUnit(s,'warden',10,14);infect(s,u,'bite',20);makeUnit(s,'hollow',11,14).hp=1;combatStep(s,.1);expect(s.resources.stone).toBe(1);const z=makeUnit(s,'hollow',11,14);z.reanimatedFrom=s.nextId++;z.hp=1;u.cooldown=0;combatStep(s,.1);expect(s.resources.stone).toBe(1);expect(s.logs[0].text).toContain('no bounty');expect(s.effects.some(e=>e.kind==='reward'&&e.note==='reanimated')).toBe(true);reload(s);});
 it('does not lose earned Crowns at the old storage cap',()=>{let s=arena();s.resources.stone=10100;makeBuilding(s,'tower',10,14,true);makeUnit(s,'brute',11,14).hp=1;combatStep(s,.1);s=reload(s);expect(s.resources.stone).toBe(10103);economyStep(s,.1);expect(s.resources.stone).toBe(10103);});
 it('first expedition kills reach the kingdom immediately; retreat/reload/repeat slots cannot repay',()=>{let s=newGame();command(s,{type:'recruit',kind:'warden'});command(s,{type:'recruit',kind:'ranger'});s.resources.stone=200;expect(command(s,{type:'expedition-launch'}).ok).toBe(true);let w=s.expedition!.world;const z=w.units.find(u=>u.bountyKey==='scout-0')!;z.hp=1;const u=army(w)[0];Object.assign(u,{x:z.x-1,y:z.y,target:{x:z.x-1,y:z.y},cooldown:0,order:'hold'});const before=s.resources.stone;combatStep(w,.1,false,undefined,s);expect(s.resources.stone).toBe(before+1);s.nextId=w.nextId;s=reload(s);expect(s.lostBattalions!.bounties).toContain('scout-0');w=s.expedition!.world;w.units=w.units.filter(u=>u.origin);for(const u of army(w))Object.assign(u,{x:10,y:16});command(s,{type:'expedition-retreat'});expect(command(s,{type:'expedition-extract'}).ok).toBe(true);s=reload(s);const duplicate=makeUnit(s,'runner',10,14);duplicate.bountyKey='scout-0';duplicate.bountyEligible=true;duplicate.hp=0;const gold=s.resources.stone;expect(awardBounty(s,duplicate,true)).toBe(0);expect(s.resources.stone).toBe(gold);});
 it('allied battalion combat pays into the same expedition claim ledger',()=>{const s=arena();s.lostBattalions={attempts:1,remaining:['warden'],recruited:0,cooldown:0};const w=arena();w.theatre='expedition';const ally=makeUnit(w,'spearman',10,14);ally.origin='battalion';const z=makeUnit(w,'runner',11,14);z.bountyKey='wave-1-0';z.hp=1;combatStep(w,.1,false,undefined,s);expect(s.resources.stone).toBe(2);expect(s.lostBattalions.bounties).toEqual(['wave-1-0']);expect(w.resources.stone).toBe(0);});
});
describe('safe building rearrangement',()=>{
 it('moves an upgraded damaged producing workplace without changing workers, income or identity',()=>{let s=newGame();const b=makeBuilding(s,'quarry',18,13,true);b.level=2;b.hp-=63;s.jobs.miners=3;command(s,{type:'job',job:'miners',delta:0});const jobs={...s.jobs},ids=s.residents!.map(r=>[r.id,r.job]),resources={...s.resources},income=rates(s),saved={...b};expect(relocationError(s,b.id,19,15)).toBeNull();expect(command(s,{type:'relocate',id:b.id,x:19,y:15})).toMatchObject({ok:true});expect(b).toEqual({...saved,x:19,y:15});expect(s.jobs).toEqual(jobs);expect(s.residents!.map(r=>[r.id,r.job])).toEqual(ids);expect(s.resources).toEqual(resources);expect(rates(s)).toEqual(income);s=reload(s);expect(s.buildings.find(v=>v.id===b.id)).toEqual(b);const crowns=s.resources.stone;economyStep(s,1);expect(s.resources.stone).toBeCloseTo(crowns+income.stone);});
 it('preserves unfinished construction effort and occupants at the old site',()=>{const s=newGame(),b=makeBuilding(s,'cottage',18,13);b.progress=.45;b.hp-=30;const r=s.residents![0];Object.assign(r,{x:b.x,y:b.y});expect(command(s,{type:'relocate',id:b.id,x:19,y:15}).ok).toBe(true);expect(b.progress).toBe(.45);expect(r.x).toBe(18);expect(r.y).toBe(13);economyStep(s,1);expect(b.progress).toBeGreaterThan(.45);reload(s);});
 it('rejects occupied, road, water, unowned and duplicate destinations without changing the original',()=>{const s=newGame(),b=makeBuilding(s,'cottage',18,13),original={...b},resources={...s.resources};for(const [x,y]of [[16,14],[14,13],[13,20],[1,1],[13,17]]){expect(command(s,{type:'relocate',id:b.id,x,y}).ok).toBe(false);expect(b).toEqual(original);expect(s.resources).toEqual(resources);}Object.assign(s.residents![0],{x:19,y:15});expect(relocationError(s,b.id,19,15)).toContain('people');});
 it('forbids moving defenses during attacks and leaves their health intact',()=>{const s=newGame(),b=s.buildings.find(b=>b.kind==='tower')!;b.hp-=70;makeUnit(s,'hollow',1,10);const before={...b};expect(command(s,{type:'relocate',id:b.id,x:19,y:15}).ok).toBe(false);expect(b).toEqual(before);});
 it('prevents enclosing a person or cutting the travel road',()=>{const s=arena();for(const[x,y]of [[17,16],[18,15],[18,17]])makeBuilding(s,'wall',x,y,true);const b=makeBuilding(s,'wall',20,17,true);makeUnit(s,'warden',18,16);expect(relocationError(s,b.id,19,16)).toContain('trap');expect(relocationError(s,b.id,14,17)).toContain('roads');});
 it('moves the existing Hearth without duplicating ownership or population',()=>{let s=newGame();const b=s.buildings.find(b=>b.kind==='hearth')!,pop=s.population;expect(command(s,{type:'relocate',id:b.id,x:19,y:15}).ok).toBe(true);s=reload(s);expect(s.buildings.filter(v=>v.kind==='hearth')).toHaveLength(1);expect(s.population).toBe(pop);});
});
describe('connected grid barriers and actual gate orientation',()=>{
 for(const rotation of [0,1] as const)it('orientation '+rotation+' blocks infected while admitting allies only across its opening',()=>{const s=arena(),b=makeBuilding(s,'gate',11,14,true);b.rotation=rotation;const across=rotation?{x:10,y:14}:{x:11,y:13},along=rotation?{x:11,y:13}:{x:10,y:14},nav=navigation(s);expect(movementBlocker(nav,across,b,true)).toBe(b);expect(movementBlocker(nav,across,b,false)).toBeUndefined();expect(movementBlocker(nav,along,b,false)).toBe(b);expect(clearMelee(s,across,{x:22-across.x,y:28-across.y})).toBe(false);reload(s);});
 it('rotation invalidates shared routes, persists and opens the proper crossing',()=>{let s=arena(),b=makeBuilding(s,'gate',11,14,true);b.rotation=0;let nav=navigation(s);expect(findPath(s,{x:10,y:14},{x:12,y:14}).some(p=>key(p)===key(b))).toBe(false);expect(command(s,{type:'relocate',id:b.id,x:b.x,y:b.y,rotation:1}).ok).toBe(true);expect(navigation(s)).not.toBe(nav);expect(findPath(s,{x:10,y:14},{x:12,y:14}).some(p=>key(p)===key(b))).toBe(true);s=reload(s);b=s.buildings.find(v=>v.id===b.id)!;expect(b.rotation).toBe(1);b.hp-=40;expect(command(s,{type:'repair',id:b.id}).ok).toBe(true);expect(b.rotation).toBe(1);b.hp=0;expect(movementBlocker(navigation(s),{x:10,y:14},{x:12,y:14},true)).toBeUndefined();});
 it('auto-connects stepped diagonal runs and corners without a physical corner leak',()=>{const s=arena();const points=[[10,14],[11,14],[11,15],[12,15],[12,16]];const walls=points.map(([x,y])=>makeBuilding(s,'wall',x,y,true));const index=barrierIndex(s.buildings);expect(barrierMask(walls[1],index)).toBe(6);expect(barrierMask(walls[2],index)).toBe(9);for(const b of walls)expect(movementBlocker(navigation(s),{x:b.x-.8,y:b.y+.8},{x:b.x+.8,y:b.y-.8},true)).toBeDefined();});
 it('rejects unsupported rotations and retains old saves without adding or changing building fields',()=>{const s=newGame(),raw=JSON.stringify(s);expect(reload(s).buildings).toEqual(s.buildings);const b=s.buildings.find(v=>v.kind==='gate')!;(b as any).rotation=2;expect(decode(JSON.stringify(s))).toBeNull();expect(decode(raw)).not.toBeNull();});
});

it('cached move previews still reject newly occupied ground and changed enclosure routes',()=>{
 const s=arena(),wall=makeBuilding(s,'wall',20,17,true);expect(relocationError(s,wall.id,19,16)).toBeNull();const u=makeUnit(s,'warden',19,16);expect(relocationError(s,wall.id,19,16)).toContain('people');u.x=18;for(const[x,y]of [[17,16],[18,15],[18,17]])makeBuilding(s,'wall',x,y,true);expect(relocationError(s,wall.id,19,16)).toContain('trap');
});

it('new gate placement validates its actual opening before charging or trapping a soldier',()=>{
 const s=arena();for(const[x,y]of [[17,16],[18,15],[18,17]])makeBuilding(s,'wall',x,y,true);makeUnit(s,'warden',18,16);const resources={...s.resources},count=s.buildings.length;
 expect(command(s,{type:'build',kind:'gate',x:19,y:16,rotation:0}).ok).toBe(false);expect(s.resources).toEqual(resources);expect(s.buildings).toHaveLength(count);
 expect(command(s,{type:'build',kind:'gate',x:19,y:16,rotation:1}).ok).toBe(true);expect(findPath(s,{x:18,y:16},{x:20,y:16})).toContainEqual({x:19,y:16});reload(s);
});
