import type {Runtime} from '../game/runtime';
import {army,hostiles,rivals} from '../game/state';
import {illnessFor} from '../game/disease';
import {LANDMARKS,strongholdCaptureError,travelError} from '../game/empire';
import {distance} from '../game/map';
import {available} from '../game/army';
import {canAfford,idle} from '../game/economy';
import {BUILDINGS,MAX_ARMY} from '../game/config';
import {repairCost} from '../game/commands';
import {kingdomOverview} from '../game/kingdomOverview';
const safe=(v:string)=>v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const amount=(n:number)=>Math.ceil(n).toLocaleString();
export function empirePanel(rt:Runtime):string{
 const s=rt.state,hero=army(s).find(u=>u.id===s.commander?.id),travellers=[...new Set([...rt.selectedIds,...(hero?[hero.id]:[])])],error=travelError(s,rt.selectedIds),other=s.empire?.reserve,war=s.march?.rival,weirward=s.march?.weirward,captureError=war?.status==='occupied'?strongholdCaptureError(s,'mossgate'):null,weirwardCaptureError=weirward?.status==='occupied'?strongholdCaptureError(s,'tallowmere'):null;
 const overview=kingdomOverview(s),localHearts=s.buildings.filter(b=>b.kind==='hearth'&&b.owner!=='rival');
 const status=s.region?s.march?.secured?(hostiles(s).length?'Contested · '+localHearts.length+' settlements':localHearts.length+' frontier settlements'):hostiles(s).length+' threats remain':'Hearthmere';
 const alerts=overview.alerts.length?`<div class="kingdom-alerts" aria-label="Kingdom alerts">${overview.alerts.map(a=>`<button class="kingdom-alert ${a.tone}" data-kingdom-alert="${a.action??''}" ${a.settlementId?`data-settlement-id="${a.settlementId}"`:''}><span>${safe(a.message)}</span><span aria-hidden="true">›</span></button>`).join('')}</div>`:'<p class="kingdom-quiet">No urgent settlement issues.</p>';
 const settlement=(site:typeof overview.settlements[number])=>{
  const world=site.active?s:other,b=world?.buildings.find(v=>v.id===site.id);if(!b)return '';
  const guards=site.fitCommitted,defense=site.buildings.filter(v=>['barracks','tower','wall','gate'].includes(v.kind)).length;
  const jobs=idle(world!),recallIds=site.active?army(world!).filter(u=>u.origin!=='battalion'&&u.id!==s.commander?.id&&u.order==='defend'&&distance(u.anchor??u.target,b)<8&&available(world!,u)).map(u=>u.id):[];
  const repairRows=site.repairs.slice(0,2).map(v=>{
   const cost=repairCost(v),safeToRepair=!hostiles(world!).some(u=>distance(u,v)<2),affordable=canAfford(s,cost),blocker=site.active?(!safeToRepair?'Clear nearby threats before repairing.':!affordable?'Need '+amount(Math.max(0,(cost.wood??0)-s.resources.wood))+' more Timber.':''):'';
   const label=site.active?'Repair':'Travel to region',action=site.active?`data-kingdom-repair="${v.id}"`:`data-kingdom-company="${site.id}"`;
   const why=site.active?blocker:'Travel with your company to repair this structure.';
   return `<div class="kingdom-repair"><span>${safe(v.name??BUILDINGS[v.kind].name)} <small>${amount(v.hp)} / ${amount(v.maxHp)} · ${amount(cost.wood??0)} Timber</small></span><button class="text-button" ${action} ${blocker?'disabled':''} title="${safe(why||'Repair this structure')}">${label}</button>${why?`<small class="kingdom-blocker">${safe(why)}</small>`:''}</div>`;
  }).join('');
  const progress=site.construction.slice(0,2).map(v=>`<div class="kingdom-build-progress"><span>${safe(v.name??BUILDINGS[v.kind].name)} <small>${Math.floor(v.progress*100)}% built</small></span><i><b style="width:${Math.max(0,Math.min(100,v.progress*100))}%"></b></i></div>`).join('');
  const isThreatened=site.threats>0;
  return `<article class="kingdom-settlement ${site.active?'active':'remote'}" data-settlement="${site.id}">
   <header class="kingdom-settlement-head"><div><span class="eyebrow">${safe(site.regionName)} · ${site.active?'HERE NOW':'TRAVEL REQUIRED'}</span><h3>${safe(site.name)}</h3><small>${jobs} unassigned regional workers</small></div><span class="kingdom-readiness ${isThreatened?'threatened':guards>=2?'ready':''}">${isThreatened?'Threat nearby':guards>=2?'Guarded':'Light guard'}</span></header>
   <div class="kingdom-settlement-stats"><span><small>FIT NEARBY</small><b>${site.fitStationed}</b><em>${site.stationed} stationed · ${guards} fit assigned · ${site.inbound} marching</em></span><span><small>RESIDENTS</small><b>${site.nearbyResidents}</b><em>within 7 tiles</em></span><span><small>BUILDINGS</small><b>${site.buildings.length}</b><em>${defense} defenses · ${site.repairs.length} damaged</em></span></div>
   ${repairRows||progress?`<div class="kingdom-work-list">${repairRows}${progress}</div>`:''}
   <div class="kingdom-actions">${site.active?`<button class="text-button" data-settlement-focus="${site.id}">View</button><button class="text-button" data-kingdom-company="${site.id}">Choose troops</button><button class="secondary" data-kingdom-defend="${site.id}" ${rt.selectedIds.length?'':'disabled'}>${rt.selectedIds.length?'Defend here · '+rt.selectedIds.length+' selected':'Defend here'}</button><button class="text-button" data-kingdom-recall="${site.id}" ${recallIds.length?'':'disabled'} title="${recallIds.length?'Send ordered guards back to your commander':'No fit soldiers are ordered to defend here'}">Recall ${recallIds.length}</button><button class="text-button" data-kingdom-build="${site.id}">Build defenses</button>`:`<button class="secondary" data-kingdom-company="${site.id}">Choose company to travel</button>`}</div>
   ${site.active?`<details class="kingdom-name"><summary>Rename settlement</summary><div><input id="settlement-name-${site.id}" maxlength="32" value="${safe(site.name)}" aria-label="Name ${safe(site.name)}"><button data-rename-settlement="${site.id}" class="text-button">Save</button></div></details>`:`<p class="kingdom-travel-note">Travel with your company to inspect buildings, repair damage and station defenders here. Soldiers travel physically; those left behind stay at their posts.</p>`}
  </article>`;
 };
 const territoryLine=overview.territories.length?overview.territories.join(' · '):'No reclaimed territories';
 return `<div class="panel-heading compact-heading"><span class="eyebrow">THE ROADS BEYOND</span><h2>Build an empire</h2><p>${status} · ${overview.settlements.length} owned settlements</p></div>
 <section class="kingdom-overview" aria-label="Kingdom Overview"><div class="kingdom-overview-title"><div><span class="eyebrow">YOUR REALM</span><h3>Kingdom overview</h3></div><span class="kingdom-territory-count">${overview.settlements.length} settlements</span></div><div class="kingdom-summary"><span><small>TERRITORIES</small><b>${overview.territories.length}</b><em>${safe(territoryLine)}</em></span><span><small>POPULATION</small><b>${overview.population} / ${overview.housing}</b><em>${overview.availableWorkers} unassigned workers</em></span><span><small>ARMY</small><b>${overview.soldiers} / ${overview.capacity}</b><em>${overview.fitSoldiers} fit soldiers ready · ${MAX_ARMY} global limit</em></span></div><div class="kingdom-stores"><span>${amount(s.resources.wood)} Timber</span><span>${amount(s.resources.stone)} Crowns</span><span>${amount(s.resources.food)} Provisions</span><span class="${overview.foodRate<0?'shortage':''}">${overview.foodRate>=0?'+':''}${(overview.foodRate*60).toFixed(0)}/min food</span></div>${alerts}<div class="section-label">SETTLEMENTS · ${overview.settlements.length}</div><div class="kingdom-settlement-list">${overview.settlements.map(settlement).join('')}</div></section>
 <div class="empire-hero"><h3>${hero?'Your commander #'+hero.id:'Choose your commander'}</h3>${hero?`<p>${Math.ceil(hero.hp)} / ${hero.maxHp} HP · ${s.commander!.xp} experience · rank ${1+Math.min(5,Math.floor(s.commander!.xp/6))}</p><button id="hero-toggle" class="primary full" ${hero.injury||illnessFor(s,hero.id)?'disabled':''}>${rt.heroMode?'Return to tactics':'Lead personally'}</button><div class="segmented hero-weapons">${(['sword','spear','bow'] as const).map((w,i)=>`<button id="weapon-${w}" data-weapon="${w}" aria-pressed="${s.commander!.weapon===w}">${i+1} ${w}</button>`).join('')}</div><p class="fine-print">Sword: fast, close. Spear: reach, slower. Bow: range, weak up close. Health stays the same when switching.</p>`:`<p>Appoint an existing fit soldier. A fallen commander stays dead; appoint a survivor to continue.</p><button id="appoint-commander" class="primary full">Appoint a commander</button>`}</div>
 <details class="army-help"><summary>Commander controls</summary><p>Lead personally: WASD/arrows move on screen, F attacks toward the cursor, 1–3 switch weapons. Click ground to walk; click infected or right-click to strike. Touch uses the direction pad and Strike. Tactics mode restores map and squad controls. Pause remains Space. Each six credited infected kills improves damage, up to five ranks; reanimated people grant no experience.</p></details>
 ${s.region&&!army(s).length?'<button id="home-watch" class="primary full">Return to the home watch</button><p class="fine-print">The company is lost. Resume command at home; no fallen soldier returns, and this region keeps its damage and threats.</p>':''}<div class="section-label">COMPANY & TRAVEL</div><p>${travellers.length} travellers, including the commander. Unselected soldiers stay at their posts.</p><div class="segmented"><button id="choose-company">Choose soldiers</button><button id="gather-road" ${!hero?'disabled':''}>Gather at road</button></div><button id="travel-region" class="primary full" ${error?'disabled':''}>${s.region?'Return to Hearthmere':'Explore Briar March'}</button><p class="fine-print">${error??'Road clear. Travel moves these actual soldiers and pauses on arrival.'}</p>
 ${s.region?`<div class="section-label">BRIAR MARCH</div><p>${s.march!.seen.length} / ${LANDMARKS.length} places discovered · ${hostiles(s).length} threats</p><div class="segmented">${LANDMARKS.filter(p=>s.march!.seen.includes(p.id)).map(p=>`<button data-landmark="${p.id}">${p.name}</button>`).join('')}</div><button id="place-outpost" class="primary full" ${!s.march!.secured&&hostiles(s).length||!hero?'disabled':''}>${s.march!.secured?'Found another settlement':'Place first outpost'} · 80 Timber + 40 Crowns</button><p class="fine-print">${s.march!.secured?'Bring two fit soldiers to a cleared site at least twelve tiles from another beacon. Two more idle residents leave Hearthmere as builders.':'Clear confirmed infected remains within seven tiles of the site. Bring two fit soldiers and leave two idle, healthy residents at home for your building crew.'} Choose open, accessible ground near the commander. Recovered stores reward the first founding only. Homes, farms, garrisons and defenses can be built across cleared wild terrain. ${s.march!.warning?'Raid warning: '+Math.ceil(s.march!.warning)+'s.':''}</p>`:`<p class="fine-print">Briar March connects through the southern road. Its river roads lead to forests, ruins, abandoned hamlets, caches, survivors and hostile camps. Clear a site to recover supplies or escort survivors home.</p>`}
 ${s.region&&war?`<div class="section-label">GLOAMWARD · MOSSGATE</div>${war.status==='unseen'?'<p>The Mossgate stronghold lies beyond the northern village. Explore with your commander to draw out the Gloamward.</p>':war.status==='occupied'?`<div class="war-card"><strong>Mossgate is defended</strong><p>${war.remaining} of 100 defenders remain · ${rivals(s,'mossgate').length} hold the field · ${war.casualties} fallen · ${war.reserve} relief troops. Break the gate, then move your line through. Relief needs a warning window to arrive.</p></div><button id="capture-stronghold" class="primary full" ${captureError?'disabled':''}>Secure Mossgate</button><p class="fine-print">${captureError??'Clear the stronghold, then capture with your commander nearby. Survivors, a damaged hall, croft and stores join your frontier.'}</p>`:'<div class="war-card"><strong>Mossgate secured</strong><p>The hall and defenders’ structures now belong to your settlement. The rescued quarter is ready to build and garrison.</p></div>'}`:''}
 ${s.region&&weirward?`<div class='section-label'>THE WEIRWARD COMPACT · TALLOWMERE</div>${weirward.status==='unseen'?`<p>${s.march!.rumors?.includes('weirward')?'Wayfarers count 150 defenders inside Tallowmere Hall: a causeway gate, an eastern postern, and relief held behind the walls. Scout the approach before committing your company.':'A raised keep watches the southern causeway. Find the wayfarers’ camp for a report on its garrison and approaches.'}</p>`:weirward.status==='occupied'?`<div class='war-card'><strong>Tallowmere commands the causeway</strong><p>${weirward.remaining} of 150 defenders remain · ${rivals(s,'tallowmere').length} hold the walls · ${weirward.casualties} fallen · ${weirward.reserve} relief troops. The Compact uses a heavier spear line, protected bowmen, and two gates. Pressure draws a warned relief company from its reserve.</p></div><button id='capture-tallowmere' class='primary full' ${weirwardCaptureError?'disabled':''}>Secure Tallowmere</button><p class='fine-print'>${weirwardCaptureError??'Defeat the full garrison, clear nearby infected, then secure the hall with your commander.'}</p>`:'<div class="war-card"><strong>Tallowmere secured</strong><p>The Weirward Hall, croft, twin gates, and remaining stores now answer to your banner. Six local survivors can sustain the new garrison.</p></div>'}`:''} ${s.region&&s.march?.secured?'<button id="outpost-build" class="secondary full">Build or improve this settlement →</button>':''}
 <details class="army-help"><summary>Shared supplies, persistent places</summary><p>Both settlements use one treasury. Staffed workers produce supplies and every resident and soldier consumes provisions, including stationed defenders. Construction, illness and encounters in the unvisited region hold until you return; damage and orders persist. No offscreen raid kills your defenders. Starvation still costs lives, so keep farms staffed.</p></details>`;
}
