import type {Runtime} from '../game/runtime';
import {army,hostiles,rivals} from '../game/state';
import {illnessFor} from '../game/disease';
import {LANDMARKS,strongholdCaptureError,travelError} from '../game/empire';
import {distance} from '../game/map';
const safe=(v:string)=>v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function empirePanel(rt:Runtime):string{
 const s=rt.state,hero=army(s).find(u=>u.id===s.commander?.id),travellers=[...new Set([...rt.selectedIds,...(hero?[hero.id]:[])])],error=travelError(s,rt.selectedIds),other=s.empire?.reserve,war=s.march?.rival,captureError=war?.status==='occupied'?strongholdCaptureError(s):null;
 const localHearts=s.buildings.filter(b=>b.kind==='hearth'),otherHearts=other?.buildings.filter(b=>b.kind==='hearth')??[];
 const status=s.region?s.march?.secured?(hostiles(s).length?'Contested · '+localHearts.length+' settlements':localHearts.length+' frontier settlements'):hostiles(s).length+' threats remain':'Hearthmere';
 const settlement=(w:typeof s,b:typeof s.buildings[number],active:boolean)=>{const name=b.name??(w.region?'Frontier settlement':'Hearthmere'),people=w.residents?.filter(r=>distance(r,b)<7).length??0,guards=army(w).filter(u=>distance(u,b)<7).length,works=w.buildings.filter(v=>v.kind!=='hearth'&&distance(v,b)<7).length;return `<div class="settlement-row"><div><strong>${safe(name)}</strong><small>${people} residents · ${guards} stationed soldiers · ${works} nearby buildings</small></div>${active?`<input id="settlement-name-${b.id}" maxlength="32" value="${safe(name)}" aria-label="Name ${safe(name)}"><button data-rename-settlement="${b.id}" class="text-button">Save name</button><button data-settlement-focus="${b.id}" class="text-button">View</button>`:'<small>Travel to revisit</small>'}</div>`;};
 return `<div class="panel-heading compact-heading"><span class="eyebrow">THE ROADS BEYOND</span><h2>Build an empire</h2><p>${status} · ${army(s).length} local soldiers</p></div>
 <div class="empire-hero"><h3>${hero?'Your commander #'+hero.id:'Choose your commander'}</h3>${hero?`<p>${Math.ceil(hero.hp)} / ${hero.maxHp} HP · ${s.commander!.xp} experience · rank ${1+Math.min(5,Math.floor(s.commander!.xp/6))}</p><button id="hero-toggle" class="primary full" ${hero.injury||illnessFor(s,hero.id)?'disabled':''}>${rt.heroMode?'Return to tactics':'Lead personally'}</button><div class="segmented hero-weapons">${(['sword','spear','bow'] as const).map((w,i)=>`<button id="weapon-${w}" data-weapon="${w}" aria-pressed="${s.commander!.weapon===w}">${i+1} ${w}</button>`).join('')}</div><p class="fine-print">Sword: fast, close. Spear: reach, slower. Bow: range, weak up close. Health stays the same when switching.</p>`:`<p>Appoint an existing fit soldier. A fallen commander stays dead; appoint a survivor to continue.</p><button id="appoint-commander" class="primary full">Appoint a commander</button>`}</div>
 <details class="army-help"><summary>Commander controls</summary><p>Lead personally: WASD/arrows move on screen, F attacks toward the cursor, 1–3 switch weapons. Click ground to walk; click infected or right-click to strike. Touch uses the direction pad and Strike. Tactics mode restores map and squad controls. Pause remains Space. Each six credited infected kills improves damage, up to five ranks; reanimated people grant no experience.</p></details>
 ${s.region&&!army(s).length?'<button id="home-watch" class="primary full">Return to the home watch</button><p class="fine-print">The company is lost. Resume command at home; no fallen soldier returns, and this region keeps its damage and threats.</p>':''}<div class="section-label">COMPANY & TRAVEL</div><p>${travellers.length} travellers, including the commander. Unselected soldiers stay at their posts.</p><div class="segmented"><button id="choose-company">Choose soldiers</button><button id="gather-road" ${!hero?'disabled':''}>Gather at road</button></div><button id="travel-region" class="primary full" ${error?'disabled':''}>${s.region?'Return to Hearthmere':'Explore Briar March'}</button><p class="fine-print">${error??'Road clear. Travel moves these actual soldiers and pauses on arrival.'}</p>
 ${s.region?`<div class="section-label">BRIAR MARCH</div><p>${s.march!.seen.length} / ${LANDMARKS.length} places discovered · ${hostiles(s).length} threats</p><div class="segmented">${LANDMARKS.filter(p=>s.march!.seen.includes(p.id)).map(p=>`<button data-landmark="${p.id}">${p.name}</button>`).join('')}</div><button id="place-outpost" class="primary full" ${!s.march!.secured&&hostiles(s).length||!hero?'disabled':''}>${s.march!.secured?'Found another settlement':'Place first outpost'} · 80 Timber + 40 Crowns</button><p class="fine-print">${s.march!.secured?'Bring two fit soldiers to a cleared site at least twelve tiles from another beacon. Two more idle residents leave Hearthmere as builders.':'Clear confirmed infected remains within seven tiles of the site. Bring two fit soldiers and leave two idle, healthy residents at home for your building crew.'} Choose open, accessible ground near the commander. Recovered stores reward the first founding only. Homes, farms, garrisons and defenses can be built across cleared wild terrain. ${s.march!.warning?'Raid warning: '+Math.ceil(s.march!.warning)+'s.':''}</p>`:`<p class="fine-print">Briar March connects through the southern road. Its river roads lead to forests, ruins, abandoned hamlets, caches, survivors and hostile camps. Clear a site to recover supplies or escort survivors home.</p>`}
 ${s.region&&war?`<div class="section-label">GLOAMWARD · MOSSGATE</div>${war.status==='unseen'?'<p>The Mossgate stronghold lies beyond the northern village. Explore with your commander to draw out the Gloamward.</p>':war.status==='occupied'?`<div class="war-card"><strong>Mossgate is defended</strong><p>${war.remaining} of 100 defenders remain · ${rivals(s).length} hold the field · ${war.casualties} fallen · ${war.reserve} relief troops. Break the gate, then move your line through. Relief needs a warning window to arrive.</p></div><button id="capture-stronghold" class="primary full" ${captureError?'disabled':''}>Secure Mossgate</button><p class="fine-print">${captureError??'Clear the stronghold, then capture with your commander nearby. Survivors, a damaged hall, croft and stores join your frontier.'}</p>`:'<div class="war-card"><strong>Mossgate secured</strong><p>The hall and defenders’ structures now belong to your settlement. The rescued quarter is ready to build and garrison.</p></div>'}`:''}
 ${s.region&&s.march?.secured?'<button id="outpost-build" class="secondary full">Build or improve this settlement →</button>':''}<div class="section-label">SETTLEMENTS · ${localHearts.length+otherHearts.length}</div><div class="settlement-list">${localHearts.map(b=>settlement(s,b,true)).join('')}${other&&otherHearts.map(b=>settlement(other,b,false)).join('')||''}</div>
 <details class="army-help"><summary>Shared supplies, persistent places</summary><p>Both settlements use one treasury. Staffed workers produce supplies and every resident and soldier consumes provisions, including stationed defenders. Construction, illness and encounters in the unvisited region hold until you return; damage and orders persist. No offscreen raid kills your defenders. Starvation still costs lives, so keep farms staffed.</p></details>`;
}
