import type {Runtime} from '../game/runtime';
import {army,enemies} from '../game/state';
import {illnessFor} from '../game/disease';
import {LANDMARKS,travelError} from '../game/empire';
export function empirePanel(rt:Runtime):string{
 const s=rt.state,hero=army(s).find(u=>u.id===s.commander?.id),travellers=[...new Set([...rt.selectedIds,...(hero?[hero.id]:[])])],error=travelError(s,rt.selectedIds),other=s.empire?.reserve;
 const status=s.region?s.march?.secured?(enemies(s).length?'Contested outpost':'Briar outpost'):enemies(s).length+' infected remain':'Hearthmere';
 return `<div class="panel-heading compact-heading"><span class="eyebrow">THE ROADS BEYOND</span><h2>Build an empire</h2><p>${status} · ${army(s).length} local soldiers</p></div>
 <div class="empire-hero"><h3>${hero?'Your commander #'+hero.id:'Choose your commander'}</h3>${hero?`<p>${Math.ceil(hero.hp)} / ${hero.maxHp} HP · ${s.commander!.xp} experience · rank ${1+Math.min(5,Math.floor(s.commander!.xp/6))}</p><button id="hero-toggle" class="primary full" ${hero.injury||illnessFor(s,hero.id)?'disabled':''}>${rt.heroMode?'Return to tactics':'Lead personally'}</button><div class="segmented hero-weapons">${(['sword','spear','bow'] as const).map((w,i)=>`<button id="weapon-${w}" data-weapon="${w}" aria-pressed="${s.commander!.weapon===w}">${i+1} ${w}</button>`).join('')}</div><p class="fine-print">Sword: fast, close. Spear: reach, slower. Bow: range, weak up close. Health stays the same when switching.</p>`:`<p>Appoint an existing fit soldier. A fallen commander stays dead; appoint a survivor to continue.</p><button id="appoint-commander" class="primary full">Appoint a commander</button>`}</div>
 <details class="army-help"><summary>Commander controls</summary><p>Lead personally: WASD/arrows move on screen, F attacks toward the cursor, 1–3 switch weapons. Click ground to walk; click infected or right-click to strike. Touch uses the direction pad and Strike. Tactics mode restores map and squad controls. Pause remains Space. Each six credited infected kills improves damage, up to five ranks; reanimated people grant no experience.</p></details>
 ${s.region&&!army(s).length?'<button id="home-watch" class="primary full">Return to the home watch</button><p class="fine-print">The company is lost. Resume command at home; no fallen soldier returns, and this region keeps its damage and threats.</p>':''}<div class="section-label">COMPANY & TRAVEL</div><p>${travellers.length} travellers, including the commander. Unselected soldiers stay at their posts.</p><div class="segmented"><button id="choose-company">Choose soldiers</button><button id="gather-road" ${!hero?'disabled':''}>Gather at road</button></div><button id="travel-region" class="primary full" ${error?'disabled':''}>${s.region?'Return to Hearthmere':'Explore Briar March'}</button><p class="fine-print">${error??'Road clear. Travel moves these actual soldiers and pauses on arrival.'}</p>
 ${s.region?`<div class="section-label">BRIAR MARCH</div><p>${s.march!.seen.length} / 3 landmarks discovered · ${enemies(s).length} threats</p><div class="segmented">${LANDMARKS.filter(p=>s.march!.seen.includes(p.id)).map(p=>`<button data-landmark="${p.id}">${p.name}</button>`).join('')}</div>${!s.march!.secured?`<button id="place-outpost" class="primary full" ${enemies(s).length||!hero?'disabled':''}>Place outpost · 80 Timber + 40 Crowns</button><p class="fine-print">Clear hostile infected and confirmed infected remains; uninfected deaths never reanimate. Bring two fit soldiers and leave two idle, healthy residents at home for your building crew. Choose open, accessible ground near the commander. Recovered stores reward the first founding only.</p>`:`<button id="outpost-build" class="secondary full">Build this settlement</button><p class="fine-print">Homes, farms, garrisons and defenses can be placed on any valid accessible open tile. Incursions approach the eastern old watch with an eight-second warning. ${s.march!.warning?'Raid warning: '+Math.ceil(s.march!.warning)+'s.':''}</p>`}`:`<p class="fine-print">Briar March connects through the southern road. Its forests, abandoned village and old watch are discovered by exploration. Clearing and founding secure the land; no map unlock purchase.</p>`}
 ${other?`<div class="section-label">${s.region?'HEARTHMERE':'BRIAR MARCH'} · OTHER SETTLEMENT</div><p>${other.population} residents · ${army(other).length} stationed soldiers · ${other.buildings.length} buildings · ${enemies(other).length} threats held</p>`:''}
 <details class="army-help"><summary>Shared supplies, persistent places</summary><p>Both settlements use one treasury. Staffed workers produce supplies and every resident and soldier consumes provisions, including stationed defenders. Construction, illness and encounters in the unvisited region hold until you return; damage and orders persist. No offscreen raid kills your defenders. Starvation still costs lives, so keep farms staffed.</p></details>`;
}
