import { battalion, equipmentReserve, expeditionParty, launchError, missionRoute, readyArmy, trusted } from '../game/expedition';
import { APPROACHES, ENCOUNTER_NAMES, ROLE_TIPS } from '../game/encounters';
import { army, enemies } from '../game/state';
import { distance } from '../game/map';
import type { Expedition, ExpeditionApproach, State, Unit } from '../game/types';
import { UNITS } from '../game/config';

export function missionObjective(e: Expedition): string {
  if (e.stage === 'retreat') return 'Withdraw to the entry banners';
  if (!e.discovered) return 'Find the Grey Pennants at the outpost';
  if (!e.held) return 'Stand with the battalion against the ambush';
  if (!e.shared) return 'Share food and medicine at the outpost';
  if (!e.standard) return 'Recover the standard and hold the ground';
  return 'Escort the survivors to extraction';
}
const roster = (units: Unit[]) => units.map(u => `<div class="exp-soldier ${u.hp < u.maxHp * .3 ? 'wounded' : ''}"><span>${u.kind === 'warden' ? 'Swordsman' : u.kind === 'ranger' ? 'Archer' : UNITS[u.kind].name}</span><span>${Math.ceil(u.hp)} / ${u.maxHp} HP</span><i style="--health:${u.hp / u.maxHp * 100}%"></i></div>`).join('');
export function expeditionPanel(s: State, selected: number[], approach: ExpeditionApproach = 'ridge'): string {
  const e = s.expedition, record = s.lostBattalions, error = launchError(s), reserve = equipmentReserve(s);
  const heading = `<div class="panel-heading"><span class="eyebrow">LOST BATTALIONS · THE GREY PENNANTS</span><h2>The Broken Standard</h2><p>They held the road when their kingdom fell. Give them a reason to stand with yours.</p></div>`;
  if (!e) return heading + (record?.report ? `<div class="exp-report"><strong>${record.report.outcome === 'success' ? 'The pennants return' : record.report.outcome === 'defeat' ? 'The patrol was lost' : 'A fighting withdrawal'}</strong><p>${record.report.returned} patrol returned · ${record.report.recruited} enlisted · ${record.report.lost} casualties · ${record.report.stranded} still stranded.</p></div>` : '') +
    `<div class="tip-box"><p><strong>One finite battalion.</strong>Fight beside ${record?.remaining.length ?? 4} stranded soldiers, share supplies, and recover their standard. Escort survivors home to enlist them. Deaths persist; rewards cannot repeat.</p></div>
    <div class="section-label">CHOOSE YOUR GROUND</div><div class="exp-approaches">${(Object.keys(APPROACHES) as ExpeditionApproach[]).map(a => `<button id="approach-${a}" data-approach="${a}" aria-pressed="${approach === a}" class="secondary full"><strong>${APPROACHES[a].name}</strong><small>${APPROACHES[a].detail}</small></button>`).join('')}</div>
    <p class="detail-description">Scouts report: <strong>${ENCOUNTER_NAMES[(s.seed + (record?.attempts ?? 0)) % 3]}</strong>. Each ambush has several warned arrivals. Use shields to screen your bowmen; you can pause to reposition.</p>
    <div class="section-label">PATROL BRIEFING</div><p class="detail-description">Three fit soldiers deploy; at least two guard home. The kingdom clock waits. Every surviving patrol member and every trusted ally must reach the entry banners to extract.</p>
    <p class="detail-description">Pack: <strong>30 food + 4 herbs</strong>. Reserve <strong>${reserve} Crowns</strong> for equipment: 20 per potential recruit. Unused equipment returns home on withdrawal, death or defeat. The travel pack is spent.</p>
    <p class="detail-description">Survivors need 20–80 peaceful seconds of rest with food above 15. A staffed refuge speeds recovery. Stranded survivors retain their wounds on a return visit.</p>
    <div class="three-stats"><div><strong>${readyArmy(s).length}</strong><small>Fit soldiers</small></div><div><strong>${record?.recruited ?? 0}</strong><small>Enlisted</small></div><div><strong>${army(s).filter(u => u.injury).length}</strong><small>Recovering</small></div></div>
    <div class="section-label">CHOOSE YOUR PATROL <span>${selected.length} / 3</span></div><div class="exp-patrol">${readyArmy(s).map(u => `<button class="secondary full" id="patrol-${u.id}" data-patrol="${u.id}" aria-pressed="${selected.includes(u.id)}">${selected.includes(u.id) ? '✓' : '+'} ${UNITS[u.kind].name} #${u.id} · ${Math.ceil(u.hp)} HP<small>${ROLE_TIPS[u.kind as keyof typeof ROLE_TIPS]}</small></button>`).join('')}</div>
    <button id="expedition-launch" class="primary full" ${error || selected.length !== 3 ? 'disabled' : ''}>Deploy · 30 food + 4 herbs + equipment</button><p class="fine-print">${error ?? 'Select three fit soldiers. Enlisted allies join your permanent army and consume provisions.'}</p><button id="expedition-back" class="secondary full">Back to the army</button>`;
  const route = missionRoute(e), foes = enemies(e.world), pending = e.pending?.length ?? 0;
  const party = expeditionParty(e), allies = battalion(e), atEntry = party.filter(u => distance(u, route.exit) < 3.5).length;
  const contested = foes.some(u => distance(u, route.standard) < 2.5);
  const extractError = atEntry !== party.length ? `${atEntry} / ${party.length} patrol at entry — gather every survivor.` : foes.some(u => distance(u, route.exit) < 4) ? 'Clear infected within four tiles of the entry.' : trusted(e) && allies.some(u => distance(u, route.exit) >= 3.5) ? 'Wait for every trusted ally to reach the entry.' : 'Extraction ground ready.';
  return heading + `<div class="exp-objective"><span class="eyebrow">CURRENT OBJECTIVE</span><h3>${missionObjective(e)}</h3><p>${e.warning > 0 ? `Ambush in ${Math.ceil(e.warning)}s. Orange markers show the approaches.` : `${foes.length} infected · ${pending} still approaching${e.wave === 2 && !e.standard ? ` · ground held ${Math.floor(e.holdTime)} / 12s${contested ? ' — contested' : ''}` : ''}`}</p></div>
    <div class="segmented formations"><button id="formation-line" data-formation="line" class="${e.world.formation === 'line' ? 'active' : ''}">Shield line</button><button id="formation-loose" data-formation="loose" class="${e.world.formation === 'loose' ? 'active' : ''}">Loose order</button></div><p class="fine-print">${e.world.formation === 'line' ? 'Nearby wardens gain 3 armor. Keep swords forward and bowmen behind.' : 'Bowmen gain 0.6 range; rally positions spread out. Watch your flanks.'} Formation spacing applies to your next rally order.</p>
    <div class="trust-list" aria-label="Battalion trust"><span class="${e.held ? 'earned' : ''}">${e.held ? '✓' : '○'} Fight beside them</span><span class="${e.shared ? 'earned' : ''}">${e.shared ? '✓' : '○'} Share food & medicine</span><span class="${e.standard ? 'earned' : ''}">${e.standard ? '✓' : '○'} Recover their standard</span></div><p class="fine-print">${trusted(e) ? 'Trust earned. Escort all living Grey Pennants to extraction.' : 'Allies fight now. Enlistment requires all three acts of trust.'}</p>
    <div class="exp-waypoints"><button id="expedition-camp" class="secondary">To outpost</button><button id="expedition-standard" class="secondary" ${!e.held || !e.shared ? 'disabled' : ''}>To standard</button><button id="expedition-exit" class="secondary">To entry</button></div><button id="rally" class="secondary full">Position patrol on the map</button>
    <button id="expedition-share" class="primary full" ${!e.discovered || e.shared || e.stage === 'retreat' ? 'disabled' : ''}>${e.shared ? 'Supplies shared' : 'Share 8 packed food + 3 herbs'}</button><p class="fine-print">Pack: ${e.supplies} food · ${e.medicine} herbs. Sharing heals allies by 25 HP and cures up to three infected allies. Stand near the outpost; timing can save a wounded ally.</p>
    <button id="expedition-treat" class="secondary full" ${!e.medicine||!e.world.infection.length?'disabled':''}>Treat most urgent ally · 1 packed herb</button><p class="fine-print">${e.world.infection.length} infected allies. Save 3 herbs to share at the outpost. Tainted deaths reanimate after 8 seconds.</p><div class="section-label">YOUR PATROL <span>${party.length} / ${e.deployed}</span></div>${roster(party)}<div class="section-label">GREY PENNANTS <span>${e.discovered ? allies.length : 'Undiscovered'}</span></div>${e.discovered ? roster(allies) : '<p class="fine-print">Find the faded pennant at the ruined outpost.</p>'}
    <button id="expedition-extract" class="primary full" ${extractError !== 'Extraction ground ready.' || !party.length ? 'disabled' : ''}>Extract at the entry banners</button><p class="fine-print">${extractError}</p><button id="expedition-retreat" class="text-button full">Order a fighting retreat</button><p class="fine-print">Withdraw before losses mount. Unfinished objectives award no recruits. Unspawned reinforcements are abandoned; existing enemies still pursue you.</p>`;
}
