import { diseaseStage, illnessDeadline } from '../game/disease';
import { capacity } from '../game/economy';
import { enemies } from '../game/state';
import type { State } from '../game/types';

export function plagueDetails(s:State):string {
  const hosts=new Map([...(s.residents??[]),...s.units].map(p=>[p.id,p]));
  const cases=[...s.infection].sort((a,b)=>illnessDeadline(s,a,hosts.get(a.personId!))-illnessDeadline(s,b,hosts.get(b.personId!))||a.id-b.id);
  const settlerReason=s.region&&!s.march?.secured?'Establish a secure outpost first.':s.phase!=='day'||enemies(s).length?'Wait for peaceful daylight.':capacity(s)-s.population<5?'Build five spare beds.':(s.musterClock??0)>0?Math.ceil(s.musterClock!)+'s before the next invitation.':s.resources.stone<20?'Need '+Math.ceil(20-s.resources.stone)+' more Crowns.':'';
  const source=(i:State['infection'][number])=>i.source==='bite'?`Zombie bite · attacker #${i.sourceId}`:i.legacyCause==='bite'?'Older save · bite recorded, attacker unknown':'Older save · original source unavailable';
  const bitten=[...(s.residents??[]),...s.units].filter(p=>p.hp>0&&p.exposureSourceId&&!cases.some(i=>i.personId===p.id));
  const livingRemains=s.corpses??[],infectedRemains=livingRemains.filter(c=>c.tainted);
  const reanimated=s.units.filter(u=>u.reanimatedFrom!==undefined).length;
  return `<div class="section-label">BITES, ILLNESS & RECOVERY</div><p class="fine-print">Only a confirmed bite from a living zombie can cause new infection. Ordinary wounds, proximity, ground and supplies cannot infect anyone. A bitten person stays human; confirmed infection incubates for 18s, becomes symptomatic, then critical at 55s. At 0 HP they die; only infected remains can reanimate after 8s. Treat infection with herbs. Cleanse at a completed Herbalist’s refuge to stop infected remains rising. Estimates use current HP; later wounds can shorten them.</p><p class="fine-print">${cases.filter(i=>i.host==='soldier').length} infected soldiers · ${infectedRemains.length} infected corpses · ${reanimated} reanimated enemies${s.quarantine?' · Quarantine active: isolates the sick and slows illness.':''}</p>
  ${cases.slice(0,12).map(i=>{const host=hosts.get(i.personId!),deadline=illnessDeadline(s,i,host),state=deadline<=8?'Dying · infected':diseaseStage(i.age);return `<button class="infection-case ${i.age>=55||deadline<=8?'critical':''}" data-person-focus="${i.personId}">${i.host==='soldier'?'Soldier':'Resident'} #${i.personId} · ${state}<small>${source(i)} · ${Math.ceil(host?.hp??0)} HP · death risk ≈ ${Math.ceil(deadline)}s</small><small>Living and treatable · Focus ${s.quarantine?'· isolated':''} →</small></button>`;}).join('')}
  ${bitten.slice(0,12).map(p=>`<button class="infection-case" data-person-focus="${p.id}">${'kind'in p?'Soldier':'Resident'} #${p.id} · Bitten · ${Math.floor(p.exposure??0)}% exposure<small>Zombie bite · attacker #${p.exposureSourceId}. Still human; no confirmed infection.</small><small>${Math.ceil(p.hp)} HP · Focus →</small></button>`).join('')}
  ${livingRemains.map(c=>`<button class="infection-case ${c.tainted?'critical':''}" data-remains-focus="${c.id}">${c.tainted?'Infected dead':'Dead'} · #${c.personId}${c.tainted?` · reanimates in ${Math.ceil(c.remaining)}s`:''}<small>${c.tainted?`Zombie bite · attacker #${c.sourceId??'unrecorded'}. Cleanse at a Herbalist’s refuge before they rise.`:'Uninfected remains cannot reanimate.'} Focus →</small></button>`).slice(0,8).join('')}
  <div class="section-label">SETTLEMENT GROWTH</div><button id="invite-settlers" class="secondary full" ${settlerReason?'disabled':''}>Invite 5 settlers · 20 Crowns</button><p class="fine-print">${settlerReason||'Five spare beds and peaceful daylight required. Available every 20 seconds.'} Unassign fit residents before recruiting them.</p>`;
}
