import {test,expect,type Page} from '@playwright/test';
import {newGame,makeBuilding,makeUnit} from '../../src/game/state';
import {BUILDINGS} from '../../src/game/config';
import {command} from '../../src/game/commands';
import type {State} from '../../src/game/types';
import {writeFile} from 'node:fs/promises';
const read=(page:Page)=>page.evaluate(()=>JSON.parse(JSON.stringify((window as any).__KINGNAMIC__.runtime.state))) as Promise<State>;
async function load(page:Page,s:State){s.speed=0;await page.addInitScript(raw=>{if(!localStorage.getItem('kingnamic.save.v2'))localStorage.setItem('kingnamic.save.v2',raw);},JSON.stringify(s));await page.goto('/');await page.locator('#start').click();}
async function inspect(page:Page,id:number){await page.locator('#tab-build').click();await page.locator('#category-owned').click();await page.locator('#inspect-'+id).click();await page.waitForTimeout(450);}
async function point(page:Page,x:number,y:number){const p=await page.evaluate(p=>(window as any).__KINGNAMIC__.scene.screenPoint(p),{x,y}),b=await page.locator('#world canvas').boundingBox();return {x:b!.x+p.x,y:b!.y+p.y};}
async function at(page:Page,x:number,y:number,touch=false){const p=await point(page,x,y);if(touch)await page.touchscreen.tap(p.x,p.y);else await page.mouse.click(p.x,p.y);}
async function roundTrip(page:Page){await page.locator('#save').click();const before=await read(page);await page.reload();await page.locator('#start').click();expect((await read(page)).buildings).toEqual(before.buildings);expect((await read(page)).resources).toEqual(before.resources);return before;}
test('desktop drag, invalid destination, cancel and confirm preserve upgraded producing workplace',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));const s=newGame(),b=makeBuilding(s,'quarry',18,13,true);b.level=2;b.hp-=63;s.jobs.miners=3;command(s,{type:'job',job:'miners',delta:0});await load(page,s);await inspect(page,b.id);await page.locator('#edit-building').click();await at(page,16,14);await expect(page.locator('#confirm-placement')).toBeDisabled();expect((await read(page)).buildings.find(v=>v.id===b.id)).toEqual(b);await page.locator('#cancel-placement').click();expect((await read(page)).buildings.find(v=>v.id===b.id)).toEqual(b);
 await page.locator('#edit-building').click();const a=await point(page,18,13),z=await point(page,19,15);await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(z.x,z.y,{steps:12});await page.mouse.up();await expect(page.locator('#confirm-placement')).toBeEnabled();expect((await read(page)).buildings.find(v=>v.id===b.id)).toEqual(b);await page.screenshot({path:'docs/evidence/correctness-move-preview.png'});await page.locator('#confirm-placement').click();let now=await read(page);expect(now.buildings.find(v=>v.id===b.id)).toEqual({...b,x:19,y:15});expect(now.jobs).toEqual(s.jobs);expect(now.resources).toEqual(s.resources);await roundTrip(page);
 const before=await read(page);await page.locator('#speed-1').click();await page.waitForTimeout(3000);await page.locator('#pause').click();now=await read(page);expect(now.resources.stone).toBeGreaterThan(before.resources.stone+1.5);expect(now.jobs.miners).toBe(3);expect(errors).toEqual([]);await page.screenshot({path:'docs/evidence/correctness-moved-workplace.png'});await writeFile('docs/evidence/correctness-edit.json',JSON.stringify({fixture:true,building:now.buildings.find(v=>v.id===b.id),jobs:now.jobs,productionEarned:now.resources.stone-before.resources.stone,errors},null,2));
});
test('touch move and rotate use visible confirmation and preserve damaged gate through reload',async({browser})=>{
 const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),page=await context.newPage(),s=newGame(),b=makeBuilding(s,'gate',18,13,true);b.rotation=0;b.hp-=80;b.level=2;
 try{await load(page,s);await inspect(page,b.id);await page.locator('#edit-building').tap();await page.waitForTimeout(450);await page.locator('#rotate-placement').tap();await at(page,19,15,true);await expect(page.locator('#confirm-placement')).toBeEnabled();expect((await read(page)).buildings.find(v=>v.id===b.id)).toEqual(b);for(const id of ['rotate-placement','confirm-placement','cancel-placement']){const box=await page.locator('#'+id).boundingBox();expect(box!.height).toBeGreaterThanOrEqual(44);expect(box!.x).toBeGreaterThanOrEqual(0);expect(box!.x+box!.width).toBeLessThanOrEqual(391);}await page.screenshot({path:'docs/evidence/correctness-touch-preview.png'});await page.locator('#confirm-placement').tap();expect((await read(page)).buildings.find(v=>v.id===b.id)).toEqual({...b,x:19,y:15,rotation:1});await roundTrip(page);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}finally{await context.close();}
});
test('new walls rotate by keyboard and connect a stepped diagonal defense through real placement',async({page})=>{
 const s=newGame();s.resources.wood=500;s.units=[];s.residents=[];s.population=0;s.jobs={farmers:0,woodcutters:0,miners:0,healers:0,builders:0};await load(page,s);await page.locator('#tab-build').click();await page.locator('#category-defense').click();await page.locator('#build-wall').click();await page.keyboard.press('r');for(const[x,y]of [[18,13],[19,13],[19,14],[20,14],[20,15]])await at(page,x,y);const now=await read(page),added=now.buildings.filter(b=>!s.buildings.some(old=>old.id===b.id));expect(added).toHaveLength(5);expect(added.every(b=>b.rotation===1)).toBe(true);expect(now.resources.wood).toBe(s.resources.wood-5*BUILDINGS.wall.cost.wood!);await page.keyboard.press('Escape');await roundTrip(page);await page.screenshot({path:'docs/evidence/correctness-connected-walls.png'});
});
test('rotated gate takes real siege damage, survives reload, breaches, and its defender earns one bounty',async({page})=>{
 const s=newGame();s.units=[];s.residents=[];s.population=0;s.jobs={farmers:0,woodcutters:0,miners:0,healers:0,builders:0};s.buildings=s.buildings.filter(b=>b.kind==='hearth');s.resources.stone=0;s.bountyPaid=40;s.completed=['build','recruit','night','claim','survive'];for(let y=0;y<26;y++){if(y===15)continue;const wall=makeBuilding(s,'wall',19,y,true);wall.hp=wall.maxHp=5000;}const gate=makeBuilding(s,'gate',19,15,true);gate.rotation=1;gate.hp=70;const defender=makeUnit(s,'warden',18,15);defender.hp=defender.maxHp=1000;defender.order='hold';const zombie=makeUnit(s,'brute',21,15);zombie.hp=55;await load(page,s);await page.locator('#speed-1').click();await expect.poll(async()=>(await read(page)).buildings.find(b=>b.id===gate.id)?.hp??0,{timeout:20000}).toBeLessThan(70);await page.locator('#pause').click();let now=await read(page);expect(now.buildings.find(b=>b.id===gate.id)?.rotation).toBe(1);expect(now.units.find(u=>u.id===zombie.id)!.x).toBeGreaterThan(19.6);await roundTrip(page);await page.locator('#speed-1').click();await expect.poll(async()=>(await read(page)).resources.stone,{timeout:40000}).toBe(3);await expect(page.locator('#bounty-feedback')).toContainText('+3 Crowns');await page.locator('#pause').click();now=await read(page);expect(now.buildings.some(b=>b.id===gate.id)).toBe(false);expect(now.units.some(u=>u.id===zombie.id)).toBe(false);expect(now.stats.slain).toBe(1);await roundTrip(page);expect((await read(page)).resources.stone).toBe(3);await page.screenshot({path:'docs/evidence/correctness-siege-reward.png'});
});

test('a reanimated enemy visibly explains its no-bounty rule instead of silently losing a reward',async({page})=>{
 const s=newGame();s.units=[];s.residents=[];s.population=0;s.jobs={farmers:0,woodcutters:0,miners:0,healers:0,builders:0};s.completed=['build','recruit','night','claim','survive'];const z=makeUnit(s,'hollow',18,17);z.hp=1;z.reanimatedFrom=s.nextId++;await load(page,s);await page.locator('#speed-1').click();await expect.poll(async()=>await page.evaluate(()=>[...(window as any).__KINGNAMIC__.scene.rewards.values()].some((t:any)=>t.visible&&t.text==='Reanimated · no bounty'))).toBe(true);await page.locator('#pause').click();const now=await read(page);expect(now.resources.stone).toBe(s.resources.stone);expect(now.logs.some(l=>l.text.includes('reanimated dead: no bounty'))).toBe(true);await page.screenshot({path:'docs/evidence/correctness-excluded-reward.png'});await roundTrip(page);
});

test('gate placement preview rejects the wrong opening and accepts rotation without trapping soldiers',async({page})=>{
 const s=newGame();s.units=[];s.residents=[];s.population=0;s.jobs={farmers:0,woodcutters:0,miners:0,healers:0,builders:0};for(const[x,y]of [[17,16],[18,15],[18,17]])makeBuilding(s,'wall',x,y,true);makeUnit(s,'warden',18,16);await load(page,s);await page.locator('#tab-build').click();await page.locator('#category-defense').click();await page.locator('#build-gate').click();const before=await read(page);const click=await point(page,19,16);expect(await page.evaluate(p=>document.elementFromPoint(p.x,p.y)?.tagName,click)).toBe('CANVAS');await at(page,19,16);expect((await read(page)).buildings).toEqual(before.buildings);expect((await read(page)).resources).toEqual(before.resources);await expect(page.locator('#toast')).toContainText('trap');await page.locator('#rotate-placement').click();await at(page,19,16);const after=await read(page);expect(after.buildings).toHaveLength(before.buildings.length+1);expect(after.buildings.at(-1)?.rotation).toBe(1);await roundTrip(page);
});
